### ISSUE TITLE
placeholder attribute is not applied to textarea tags

### ISSUE THREAD

**Issue by z3cka** [getgrav/grav-plugin-form#10]
It seems that 
```yaml
- name: detailed-description
      label: Detailed description
      placeholder: 'including learning outcomes, for proposal review (up to 250 words)'
      type: textarea
```
outputs:
```html
<textarea rows="10" class="form-control" name="detailed-description"></textarea>
```
missing the placeholder attribute
