### ISSUE TITLE
File upload does not work on themes such as Gravstrap (Box not clickable, no text appears in box)

### ISSUE THREAD

**Issue by nouyang** [getgrav/grav-plugin-form#113]
File upload works with `antimatter` theme but not many others.

The error looks like so:

![grav-form-debug](https://cloud.githubusercontent.com/assets/764681/21168999/6fe27490-c186-11e6-893b-a41056ef9d05.png)

With file

`user/pages/02.form/form.md`
```
---
title: Milestones
slug: milestones
template: form
 
 
form:
    name: contact
 
    fields:
        - name: my_file
          type: file
          label: upload Label
          destination: '@self'
          multiple: true
          accept:
           - image/*
 
    buttons:
        - type: submit
          value: Submit


        - type: reset
          value: Reset
 
    process:
        - save:
        - message: Thank you for getting in touch!
        - display: thankyou
 
---
``` 

On "deliver" theme, https://github.com/getgrav/grav-theme-deliver, to fix, add one line:
`/user/themes/[theme]/templates/partials/base.html.twig`

    {{ assets.js('bottom') }}

in pre-existing "bottom" block.

See https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig#L84
and
https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/fields/file/file.html.twig#L78

However, in gravstrap theme, https://github.com/giansi/gravstrap-theme-skeleton, 
adding the lines

```
    {% block bottom %}
      {{ assets.js('bottom') }}
    {% endblock %}
```

results only in new errors in console (originally no console errors despite box not working);

```
Uncaught ReferenceError: GravForm is not defined(…)
Uncaught Error: No URL provided.(…)
```

:( How can I get the file upload in forms in this theme to work?
