### ISSUE TITLE
Problems with multi-language form and cache

### ISSUE THREAD

**Issue by Sergiop79** [getgrav/grav-plugin-form#118]
Hi

I'm doing a multilingual grav site in Spanish and English. The first language is Spanish.

Creating the contact form it has 2 fields: Email and message.

I would like to be the labels translatable. I followed the documentation to create the contact form <https://learn.getgrav.org/forms/forms>

These are the frontmatters for both languages:

Spanish

```yaml
---
title: Contacto
published: true
date: '05-01-2017 12:09'
slug: contacto
cache_enable: false
body_color: '#FAEBD2'
cache:
    enabled: false
form:
    name: contact-form
    fields:
        -
            name: email
            label: Email
            id: email
            type: email
            validate:
                required: true
        -
            name: message
            label: Mensaje
            id: message
            type: textarea
            validate:
                required: true
        -
            name: send_copy
            type: checkbox
            label: 'Envíame una copia de este mensaje'
            id: send_copy
    buttons:
        -
            type: submit
            value: Enviar
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: ['{{ config.plugins.email.from }}', '{{ form.value.send_copy ? form.value.email : config.plugins.email.from }}']
                subject: 'Mensaje desde Kamatiko web | Kamatiko.net'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Gracias por tu feedback!'
        -
            display: gracias
---

```

English

```yaml
---
title: Contact
published: true
date: '05-01-2017 12:09'
slug: contact
cache_enable: false
body_color: '#FAEBD2'
cache:
    enabled: false
form:
    name: contact-form
    fields:
        -
            name: email
            label: Email
            id: email
            type: email
            validate:
                required: true
        -
            name: message
            label: Message
            id: message
            type: textarea
            validate:
                required: true
        -
            name: send_copy
            type: checkbox
            label: 'Send me a copy of the message'
            id: send_copy
    buttons:
        -
            type: submit
            value: Submit
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: ['{{ config.plugins.email.from }}', '{{ form.value.send_copy ? form.value.email : config.plugins.email.from }}']
                subject: 'Message from Kamatiko web | Kamatiko.net'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Thanks for your feedback'
        -
            display: gracias
---
```

The cache on the site is enabled, and on the frontmatter of the page is supposed to be disabled.

When I enter to spanish page the labels are in spanish. When i enter on english page the labels still in spanish.

If I clean all the cache on the site and enter first to the english page the label are in english. Then, when going to the spanish page, the labels still in english.

If I disable the cache on all the site and clean it, the labels are translated well to their language.

I think there is a problem with the cache.

Can anybody help me?

Thanks

Sergio

**Comment by flaviocopes** [comment]
Mmm, I tested but I cannot replicate the problem with cache enabled.

**Comment by Sergiop79** [comment]
@flaviocopes can you try to replicate the problem with this configuration?

Thanks

/user/config/system.yaml

```yaml
absolute_urls: false
timezone: Europe/Madrid
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
force_ssl: false
languages:
  supported:
    - es
    - en
  include_default_lang: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
home:
  alias: /home
  hide_in_urls: false
pages:
  theme: kamatiko
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    short: 'jS M Y'
    long: 'F jS \a\t g:ia'
  publish_dates: true
  process:
    markdown: true
    twig: true
  twig_first: false
  never_cache_twig: true
  events:
    page: true
    twig: true
  markdown:
    extra: false
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - txt
    - xml
    - html
    - htm
    - json
    - rss
    - atom
  expires: 604800
  last_modified: false
  etag: false
  vary_accept_encoding: false
  redirect_default_route: false
  redirect_default_code: '301'
  redirect_trailing_slash: true
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  frontmatter:
    process_twig: true
    ignore_fields:
      - form
      - forms
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: g
  lifetime: 604800
  gzip: false
  allow_webserver_gzip: false
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  umask_fix: false
assets:
  css_pipeline: false
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: false
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: true
  js_minify: true
  enable_asset_timestamp: false
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
errors:
  display: '1'
  log: true
debugger:
  enabled: false
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 85
  cache_all: false
  cache_perms: '0755'
  debug: false
  auto_fix_orientation: false
media:
  enable_media_timestamp: false
  upload_limit: 0
session:
  enabled: true
  timeout: 1800
  name: grav-site
  secure: false
  httponly: true
  split: true
gpm:
  releases: stable
  method: auto
  verify_peer: true
```

**Comment by Sergiop79** [comment]
Finally I solve the problem introducing the languages strings as values of the labels, like this:

```yaml
form:
    name: contact-form
    fields:
        -
            name: email
            label: KAMATIKO.EMAIL
            id: email
            type: email
            validate:
                required: true
        -
            name: message
            label: KAMATIKO.MESSAGE
            id: message
            type: textarea
            validate:
                required: true
        -
            name: send_copy
            type: checkbox
            label: KAMATIKO.SEND_COPY
            id: send_copy
```

Now it works well

Thankyou
