### ISSUE TITLE
Select and checkbox fields return options keys instead of values

### ISSUE THREAD

**Issue by vladzhigulsky** [getgrav/grav-plugin-form#121]
Currently the select and checkbox fields return the key names rather than values on thank you page and email.

For example:

```
name: mark
label: Question
type: select
options:
  default: Select an option
  option1: Answer 1
  option2: Answer 2
  option3: Answer 3
  option4: Answer 4
```

If option1 was selected I would like **Answer 1** to be returned, but instead **option1** is being returned which has no meaning to the client. The same happens with the checkbox. If it was selected just 1 (true) is being returned. Instead would be nicer to see 'Yes' or 'No' for example.

Is it currently possible to achieve via configuration without having to rewrite the twig templates?
