### ISSUE TITLE
[enhancement] Add step attribute to range field

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-form#136]
it will useful to have step attribute in range field
so when you have for instance `min: 0` `max: 1000` `step: 100` the slider will change every 100

Thanks

**Comment by dimitrilongo** [comment]
thanks

**Comment by sphism** [comment]
Awesome, just came across this myself, was expecting step to work but it didn't.

**Comment by manuel-84** [comment]
With this configuration it's not working properly:

```
                  type: range
                  validate:
                    min: 0
                    max: 1
                    step: 0.1
```
