### ISSUE TITLE
Fieldset validating issue

### ISSUE THREAD

**Issue by jraack** [getgrav/grav-plugin-form#140]
Hi Guys,

I just found an issue with the fieldset. I have a form based on the fields syntax.
When i add fields under a fieldset it is not validating my input fields if they are required?

```yaml
form:  
  fields:    
    -
        name: email
        outerclasses: medium-12 columns
        placeholder: E-mail adres
        type: email
        validate:
          required: true
          message: PLUGIN_LOGIN.EMAIL_VALIDATION_MESSAGE
    -
        type: fieldset
        outerclasses: row
        fields:            
        -
            name: newsletter
            outerclasses: medium-12 columns
            type: checkbox
```

Or do i missing something?
Issue ref [Fieldset support](https://github.com/getgrav/grav-plugin-form/issues/125)

Best,
Joe

**Comment by bobbwal** [comment]
Hi, what's your frontmatter look like?

**Comment by jraack** [comment]
`
---
form:  
  fields:    
    -
        name: email
        outerclasses: medium-12 columns
        placeholder: E-mail adres
        type: email
        validate:
          required: true
          message: PLUGIN_LOGIN.EMAIL_VALIDATION_MESSAGE
    -
        type: fieldset
        outerclasses: row
        fields:            
        -
            name: newsletter
            outerclasses: medium-12 columns
            type: checkbox
            label: Ik ga akkoord met de Algemene Voorwaarden.
        -
            name: newsletter
            outerclasses: medium-12 columns
            type: checkbox
            label: Ja, ik wil graag op de hoogte blijven van nieuws over Lemtrada.
        -
            name: big
            type: radio
            label: Heeft u een BIG nummer?
            outerclasses: big-box medium-12 columns
            default: markdown        
            validate:
                required: false
            options:
                true: Ja
                false: Nee             
        -
            name: bignummer
            placeholder: Uw BIG nummer
            outerclasses: big-validation medium-12 columns
            type: text
        -
            name: geboortedatum
            placeholder: Uw geboortedatum
            outerclasses: big-validation medium-12 columns
            type: text  
`

**Comment by bobbwal** [comment]
Hmm, looks in order to me. Does the fieldset need a name? Also, there aren't any required fields within the fieldset here?

**Comment by jraack** [comment]
@bobbwal thanks for your reply; i have updated the yaml, this is now my frontmatter.

**Comment by bobbwal** [comment]
All I can suggest is try adding a name for the fieldsets. Sorry I can't be more help.
```yaml
name: first-set
type: fieldset
fields:
```
