### ISSUE TITLE
Nested fields error

### ISSUE THREAD

**Issue by bobbwal** [getgrav/grav-plugin-form#141]
Since updating to 2.4.0 I'm getting the following error when I submit my form:

>  Twig_Error_Runtime
An exception has been thrown during the rendering of a template ("Object of class Grav\Common\Data\Data could not be converted to string").

data.txt.twig

**Comment by rhukster** [comment]
can you give a screenshot of full errors?  Set errors display to 1.

**Comment by bobbwal** [comment]
Here you go, the stack trace is a bit long so I've attached it as txt file.
![error](https://cloud.githubusercontent.com/assets/391847/25295669/671df990-26dc-11e7-80a1-2989f099cbd1.jpg)
[stack-trace.txt](https://github.com/getgrav/grav-plugin-form/files/948289/stack-trace.txt)

**Comment by rhukster** [comment]
Thanks, can you also provide me a copy of your form definition from the YAML frontmatter of the page?

**Comment by bobbwal** [comment]
No probs, thanks
```
---
title: 'Project Form'

form:
    name: contact-form
    classes: step-form
    fields:
        - name: set1
          type: fieldset
          fields:
            - name: final
              label: final
              type: textarea
              classes: project-final
              rows: 5
              # validate:
              #   required: true

    buttons:
        - type: button
          value: '&laquo; Previous'
          classes: previous btn btn-default
        - type: button
          value: Next &raquo;
          classes: next btn btn-info
        - type: submit
          value: Submit
          classes: submit

    process:
        # - email:
        #     from: "{{ config.plugins.email.from }}"
        #     to:
        #       - "{{ config.plugins.email.from }}"
        #       - "{{ form.value.email }}"
        #     subject: "[Feedback] {{ form.value.name|e }}"
        #     body: "{% include 'forms/data.html.twig' %}"
        - save:
            fileprefix: feedback-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        - message: Thank you for your feedback!
        - display: thankyou
---
# Project Form

```
