### ISSUE TITLE
modular Form doesn't save

### ISSUE THREAD

**Issue by multiplaie** [getgrav/grav-plugin-form#142]
hello everyone, i try to add a contact form on my homepage but when i submit, it doesn't save the result in user/data folder. there is the form.md

```
---
cache_enable: false
title: Contact
content:
    items: '@self.modular'
form:
    action: '/#contact'
    name: contact-form
    fields:
        -
            name: name
            label: 'Votre nom / pseudo'
            placeholder: 'Entrez vortre nom ou votre pseudo'
            autofocus: 'off'
            autocomplete: 'off'
            type: text
            validate:
                required: true
        -
            name: email
            label: 'Votre adresse email'
            placeholder: 'entrez votre adresse email'
            type: email
            validate:
                required: true
        -
            name: message
            label: 'Votre message'
            placeholder: 'Entrez votre message'
            type: textarea
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Envoyer
    process:
        -
            save:
                fileprefix: question-homepage-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Thank you for your feedback!'
        -
            display: thanks
---

##### UNE QUESTION ?
```

i try to add forms/data.txt.twig file into my theme but still  not fix

thanks
