### ISSUE TITLE
Problems with multi-language and redirect_trailing_slash: true and home page

### ISSUE THREAD

**Issue by linvinus** [getgrav/grav-plugin-form#143]
If form is on the home page and grav is in multilingual mode then form action  always contain trailing slash (i.e <form action ="/en/"), so when option `redirect trailing slash`  is `true`  instead of  posting form data, the 301 redirect is occurred.

system.yaml
```
languages:
  supported:
    - ru
    - en
home:
  alias: /start
redirect_trailing_slash: true
```
user/pages/01.start.en.md
```
---
...
form:
    name: contact_form
....
---
```
