### ISSUE TITLE
Unable to submit form from iPhone

### ISSUE THREAD

**Issue by kaladivo** [getgrav/grav-plugin-form#145]
Hi, on my page. I have this form:

``` 
form: 
    name: kontaktni-formular
    classes: row
    action: '#kontaktni-formular'
    reset: true
    fields:
        -
            name: name
            label: Jméno
            placeholder: Jméno
            autocomplete: 'on'
            outerclasses: 'gr-6 gr-12@small'
            type: text
            validate:
                required: true
                message: 'Vyplňte prosím jméno'
        -
            name: surname
            label: Příjmení
            placeholder: Příjmení
            outerclasses: 'gr-6 gr-12@small'
            type: text
            validate:
                required: true
                message: 'Vyplňte prosím příjmení'
        -
            name: phone
            label: 'Telefoní číslo'
            placeholder: 'Tel. číslo'
            outerclasses: 'gr-6 gr-12@small'
            type: text
            validate:
                message: 'Vyplňte prosím tel. číslo'
        -
            name: email
            label: Email
            placeholder: E-mail
            outerclasses: 'gr-6 gr-12@small'
            type: text
            validate:
                message: 'Vyplňte prosím email'
        -
            name: message
            label: Zpráva
            placeholder: Zpráva
            outerclasses: gr-12
            type: textarea
            validate:
                required: true
                message: 'Vyplňte prosím zprávu'
    buttons:
        -
            type: submit
            classes: 'submit button'
            value: Odeslat
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: [kaladivo@gmail.com]
                subject: 'Zpráva přes kontaktní formulář'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Zpráva byla úspěšně odeslána.'
        -
            reset: true
```

Whenever I submit this form on an iPhone SE (iOS version 10.3.1), it fails with this alert `Oops there was a problem, please check your input and submit the form again.`, even though every field is filled correctly. 

Is that a bug or am I doing something wrong?
