### ISSUE TITLE
Upload doesn't work on Pages  but works in Admin

### ISSUE THREAD

**Issue by zanami** [getgrav/grav-plugin-form#148]
Form 2.5.0
Mac local using php -S localhost:8000 system/router.php
Linux / nginx

I have a Page like this
test.md
```
---
title: 'Some test'
form:
    name: upload-form
    caption: Test
    title: 'Test upload'
    description: Whatever
    fields:
        -
            name: name
            label: Name
            placeholder: 'Name *'
            type: text
            validate:
                required: true
        -
            name: attachment
            label: Attachment
            type: file
            multiple: false
            destination: 'self@'
            accept:
                - application/pdf
                - application/x-pdf
                - application/zip
    buttons:
        -
            type: submit
            value: Send
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: some-mail-here@gmail.com
                subject: '[Contact] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
                attachments: [attachment]
        -
            save:
                fileprefix: contact-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: Thank you!
---

It's a test
```

Template is simple, I don't have form.html.twig in my theme so I the default plugin template should be used, right?

test.html.twig
```
{% extends 'partials/base.html.twig' %}
{% block header %}{% endblock %}
{% block content %}
    {{ page.content }}
    {% include 'forms/form.html.twig' %}
{% endblock %}
{% block footer %}{% endblock %}
```
Browser 1 (Chrome)
Look like everything is fine  — ajax upload is there and it behaves like normal, but It doesn't upload the file. I couldn't find it anywhere.
Browser 2 (Safari)
"Oops there was a problem, please check your input and submit the form again." I can't also log in to Admin in Safari — Invalid security token. I guess it has something to do with session.
Browser 3 (Firefox)
Same as Chrome

Anyway in all 3 browsers I don't see any files uploaded.

_SESSION
```
array:4 [
  "user" => Grav\Common\User\User {#101
    #gettersVariable: "items"
    #items: []
    #blueprints: null
    #storage: null
    #nestedSeparator: "."
  }
  "redirect_after_login" => "/test"
  "files-upload" => null
  "PHPDEBUGBAR_STACK_DATA" => []
]
```
_POST
```
array:3 [
  "data" => array:2 [
    "name" => "11e1e"
    "_json" => array:1 [
      "attachment" => "null"
    ]
  ]
  "__form-name__" => "upload-form"
  "form-nonce" => "ab95618b8e1263d6d33d24235a6d71e3"
]
```

Email works but I only have the name field in it.

Meanwhile I can use Admin to upload files (attach media to Pages) no problem.
