### ISSUE TITLE
Passing grav.user.username to form

### ISSUE THREAD

**Issue by GeorgesPapas** [getgrav/grav-plugin-form#150]
I'm receiving an error when trying to pass the username variable to a form? in twig it would be {{grav.user.username}} , but I can't seem to get the hidden field of the form plugin to cooperate with this. This section of form.md looks like this

```
fields:
   -
     name: creator
     type: hidden
     default: {{grav.user.username}}
```
I keep getting the following error

`Malformed inline YAML string: admin at line 31 (near "default: admin").`

What's particularly strange to me is that it seems  the twig variable {{grav.user.username}} is being processed because its being rendered as _admin_, but I'm still getting this error.

Is this somehow expected behaviour? or am I going about this wrong?
