### ISSUE TITLE
Process Block ignored

### ISSUE THREAD

**Issue by KillianLoiseau** [getgrav/grav-plugin-form#156]
Hi, 
I'm trying to create a Contact form using the form plugin but the process block which is supposed to send the mail is ignored. Can you please tell me what I'm doing wrong.
Here's the form code : 
``` yaml
cache_enable: false
form:
    name: contact-form
    action : /contact
    fields:
        - name: Prénom et nom
          label: Prénom et nom
          class: "form-control"
          placeholder: ex: Jean Dupond
          autofocus: on
          autocomplete: on
          type: text
          validate:
            required: true
    buttons:
        - type: submit
          value: Envoyer
        - type: reset
          value: Annuler
    process:
        - email:
          subject: "Contact test"
          body: "test "
          from: "test@email.com"
          to: "test@email1.com"
```

I put debug logs in onFormProcess of grav email plugin but the log was not called, this is why i think that it's a form problem and not an email problem
