### ISSUE TITLE
Problems with form.json.twig

### ISSUE THREAD

**Issue by jmbelloteau** [getgrav/grav-plugin-form#162]
When trying to use this template in a form like this:

```yaml
title: Contact
form:
    name: contact
    template: form.json

    fields:
        - name: message
          label: false
          placeholder: Message
          type: textarea

    buttons:
        - type: submit
          value: Submit

    process:
        - message: Thank you.
```

I'm getting an error `"Template \"form.json.html.twig\" is not defined."`

I guess it's a little bug as `html.twig` seem to be append every time.
