### ISSUE TITLE
problem with response and ajax

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-form#163]
Hi,

I'm working on an Ajax form that use your plugin and I'm having some issues.

I've follow the Grav tutorial for the base and it works great. The form is processed and the response message is properly append to `<div class="contact-response"></div>`.

As the basic worked I tried to make some test with `js` to understand how your plugin works.
The objective was to catch the 'status' and the `message` from the server for every case.

Here is the script I use:

```js
$(document).ready(function(){

let contactForm = $('#contact')

contactForm.on('submit', function (event) {
    event.preventDefault()
    $.ajax({
      url: contactForm.attr('action'),
      type: contactForm.attr('method'),
      data: contactForm.serialize(),
      dataType: 'html',
      success: (message, status) => {
        console.log('ajax success:\n\n- status: ' + status + '\n\n- message: ' + message)
      }
    })
  })
});
```

To see all cases scenario I've `force`the form to return an error by changing the value of the `form-nonce` input or by adding a value to `honeypot` input.

In the end that script reveals two problems:

- **first:** the `status` from response is alway equal to `success`. The `status` never return `error` as it should. (however I see you are handling that in `classes/form.php`)
_Having the good `status` return to `js`would be very useful to create better `User XP`_

- **second:** the `message` from response looks good on **`success`**:
```html
<div class="alert notices green"><p>Thank you . I will contact you shortly.</p></div>
```
- **but on `error`** it returns the complete html page with the error` message` append inside `{{ page.content }}`:
```html
<html>
<body>
// page content
<div class="alert notices red"><p>Oops there was a problem, please check your input and submit the form again.</p></div>
</body>
</html>
```

Hope everything is clear, let me know if you need more informations.

Thank you

**Comment by jmbelloteau** [comment]
I've just make more tests and it appears that with JSON workflow using `form.json.twig` I've got the same issues. It's even worse as the response message always contain the full html code of the page with the error ` message` append inside `{{ page.content }}` like describe in first comment

**Comment by jimblue** [comment]
Hi! Any news about this?

**Comment by jimblue** [comment]
Hi @rhukster, did you read this issue?

**Comment by rhukster** [comment]
Sorry i've been busy with getting Grav 1.3 and Admin 1.5 released.  I'll try to take a look at this during the week.

**Comment by jimblue** [comment]
Hi @rhukster!
No worries about this, I was just wondering if you missed the post.
Thanks for answer!

**Comment by flaviocopes** [comment]
@jimblue this PR https://github.com/getgrav/grav-plugin-form/pull/172 should handle this problem by returning a 500 error when calling the `.json` page endpoint. Can you test it?

**Comment by rhukster** [comment]
I'm not sure returning 500 error is the correct response.  Calling a form with `.json` extension for submission seems a valid option, just any response should also be returned as json.

**Comment by jimblue** [comment]
Hi guys, sorry I've been in a hurricane this last ten days.
@flaviocopes this will no return the appropriate message an error for each case.
@rhukster yes that's exactly the good behaviour.

**Comment by rhukster** [comment]
I think i've fixed the issue with the whole HTML page being returned on error. I was able to replicate this and fix it for the HTML version of the Ajax form.  However, I'm not sure how to accurately replicate your JS test.  Can you provide me with the full page including the the form, and anything custom you've done so i can test it?

**Comment by jimblue** [comment]
Hi @rhukster !

Thanks for the fix, I just tried the last update and it seems to work great 👍 

There is only one thing to improve, actually the json response from the form always return a status of `success`, even if there is an `error`.

Here is the form:

```yaml
---
title: Contact
form:
    name: contact
    template: form-messages
    fields:
        -
            name: firstname
            label: false
            placeholder: 'First Name'
            autofocus: true
            autocomplete: true
            type: text
            validate:
                required: true
        -
            name: lastname
            label: false
            placeholder: 'Last Name'
            autocomplete: true
            type: text
            validate:
                required: true
        -
            name: email
            label: false
            placeholder: Email
            autocomplete: true
            type: email
            validate:
                required: true
        -
            name: phone
            label: false
            placeholder: Phone
            autocomplete: true
            type: tel
        -
            name: message
            label: false
            placeholder: Message
            type: textarea
            validate:
                required: true
        -
            name: honeypot
            type: honeypot
    buttons:
        -
            type: submit
            value: Submit
    process:
        -
            email:
                subject: 'Message from {{ form.value.firstname|e }} {{ form.value.lastname|e }}'
                body: [{ content_type: text/html, body: '{% include ''emails/message_admin_receipt.html.twig'' %}' }, { content_type: text/plain, body: '{% include ''forms/data.txt.twig'' %}', charset: iso-8859-1 }]
        -
            save:
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Thank you {{ form.value.firstname|e }}. I will contact you shortly.'
---
```

and there is the js to test success, error:

```js
$(document).ready(function(){

  let contactForm = $('#contact')
  let responseOutput = $('.contact-response')

  // FORM SUBMISSION
  contactForm.on('submit', function (event) {
    // PREVENT DEFAULT FORM SUBMISSION
    event.preventDefault()

    // SUBMIT THE FORM VIA AJAX
    $.ajax({
      url: contactForm.attr('action'),
      type: contactForm.attr('method'),
      data: contactForm.serialize(),
      dataType: 'html',
      // ON AJAX SUCCES
      success: (message, rules) => {
        responseOutput.html(message)
        console.log(rules)

        // IF JSON RETURN 'success' as statut
        if (status === 'success') {
          console.log('this is a SUCCESS !!!')
        }

        // IF JSON RETURN 'error' as statut
        if (status === 'error') {
          console.log('this is an ERROR !!!')
        }
      }
    })
  })
})
```

Let me know if you need more informations

**Comment by rhukster** [comment]
Ok, here's the problem.. I've implemented a quick solution that basically allows a status code to be set for a form, then in the `partials/form-messages.html.twig` i can set said code if a message is 'red', ie an error.  However, if i set this to `400` as a good error call should be, the browser doesn't render the html response.  I think only a `2xx` message will render, but that's not really accurate.

I could set it to something a bit ambiguous like `207` which means multi-status, and then you could inspect the code directly in the JS and look for that value.  Anyway i'll create a feature, and you guys can take a look.

**Comment by rhukster** [comment]
Please check out the feature branch above.. It should work with standard Grav as long as you have `undefined_functions: true` in system.yaml.

**Comment by rhukster** [comment]
![ajax test-form grav 2017-10-02 17-36-59](https://user-images.githubusercontent.com/1084697/31104127-59113a50-a798-11e7-8ab6-4114588cbc7a.png)

**Comment by jimblue** [comment]
Working well with ajax now!

**Comment by jimblue** [comment]
@rhukster don't know if you read my comment about having on option to change red class? should I create a feature request?

**Comment by rhukster** [comment]
Yah new issue would be good

**Comment by Sogl** [comment]
@jimblue @rhukster First of all, thank you guys for deep explanation and examples.

I have the same problem. I use [noty](https://github.com/needim/noty) to handle my form submit messages and latest Form plugin 2.10.0. 

My form code:
```yaml
form:
    name: send-form
    template: form-messages
    #stop sending twice
    refresh_prevention: true

    fields:
        name:
            label: Name
            placeholder: Your name
            outerclasses: 'six columns'
            type: text
            validate:
                required: true

        mail:
            label: Email
            type: email
            placeholder: my@mail.com
            outerclasses: 'six columns'
            validate:
              rule: email
              required: true

        message:
            label: Message
            placeholder: Small message
            outerclasses: 'twelve columns'
            type: textarea
            validate:
                required: true

        honeypot:
            type: honeypot

    buttons:
        submit:
            type: submit
            value: Send

    process:
        message: 'Thank you!'
```
Here is my js code:
```js
var form = $('#send-form');
   form.submit(function(e) {
       // prevent form submission
       e.preventDefault();

       // submit the form via Ajax
       $.ajax({
           url: form.attr('action'),
           type: form.attr('method'),
           dataType: 'html',
           data: form.serialize(),
           success: function(result, status) {

                console.log(result);
                console.log(status);

               new Noty({
                   theme: 'metroui',
                   layout: 'topCenter',
                   type: 'success',
                   text: result,
                   timeout: 4000
               }).show();
           }
       });
   });
```

And I see `success` status in my console when I fill honeypot field (`Are you a bot?` message) and when I try to re-submit my form (`This form has already been submitted.` message). 

Is this problem still in development?
