### ISSUE TITLE
IE10 dropzone issue 

### ISSUE THREAD

**Issue by theliveseven** [getgrav/grav-plugin-form#164]
Dropzone file uploader is not working for **IE10**. Tried in a fresh installation as well.

**_Tested on Windows 7, IE10 using virtual box._**

```
SCRIPT5022: No URL provided. 
form.min.js, line 1 character 11574
```

This is the code responsible for generating previous error in **from.min.js**.

`if (null == this.options.url && (this.options.url = this.element.getAttribute("action")), !this.options.url) throw new Error("No URL provided.");`
<img width="994" alt="screen shot 2017-07-04 at 1 41 07 pm" src="https://user-images.githubusercontent.com/12976666/27815965-cdc30996-60cb-11e7-8715-ab8b312c7db3.png">

**Comment by flaviocopes** [comment]
Can you paste the form definition (page header)?

Is this just happening on IE10 or you tried other browsers as well?

**Comment by theliveseven** [comment]
```
forms:
    application-form:
        fields:
            name:
                type: text
                label: Name
                validate: { required: true, message: 'Please enter your name!' }
            email:
                type: text
                label: Email
                validate: { type: email, required: true, message: 'Please enter a valid email address' }
            phone:
                type: text
                label: 'Phone (no spaces)'
                validate: { pattern: '[0-9]{10}', required: true, message: 'Please enter a valid phone number.' }
            position:
                type: text
                label: Position
                disabled: true
            message:
                type: textarea
                label: 'Additional Comments'
                validate: { min: 10, message: 'Email message needs to be more than 10 characters long.' }
            fileupload:
                name: fileupload
                label: 'Please upload your resume, cover letter and answers to key selection criteria as PDF here (Max file size: 20MB)'
                type: file
                multiple: true
                limit: 10
                filesize: 20
                avoid_overwriting: true
                destination: user/data/applications
                accept: [application/pdf, application/x-pdf, image/png, text/plain]
            g-recaptcha-response:
                name: g-recaptcha-response
                label: Captcha
                type: captcha
                recaptcha_site_key: xxxxxxxxx
                recaptcha_not_validated: 'Captcha not valid!'
                validate: { required: true }
        buttons:
            submit:
                type: submit
                value: Submit
        process:
            captcha:
                recatpcha_secret: xxxxxxxxx
            email:
                from: noreply@srcentre.com.au
                to: '{{ config.plugins.email.to }}'
                subject: 'Job Application - Corporate'
                body: '{% include "forms/data.html.twig" %}'
                attachments: [fileupload]
            message: 'Thank you for applying!'
            display: /forms/thankyou
```

I have tested on other browsers such as chrome, firefox and safari, not a single error on JS console either. Only happens in IE10. Hasn't tested on IE11. Will update the test results soon.
