### ISSUE TITLE
reCAPTCHA is ignored and form is sent

### ISSUE THREAD

**Issue by lid3rs** [getgrav/grav-plugin-form#168]
While having:

```
     - name: g-recaptcha-response
        size: "col-12 col-md-8"
        type: captcha
        recaptcha_site_key: 4567890
        recaptcha_not_validated: 'Captcha not valid!'
        validate:
          required: true
```
**Plguin updated to latest, grav updated to latest. Using form as a module on multiple pages.**

The validation is not working. If the recaptcha is not checked, the form is sent anyway.

![rec](https://user-images.githubusercontent.com/1872001/28021374-4a058b3c-6590-11e7-97ee-1a3820cf043f.gif)
