### ISSUE TITLE
Form shows on login protected page

### ISSUE THREAD

**Issue by rafaelpini** [getgrav/grav-plugin-form#170]
I have the Login Plugin installed and working on my site, but when I create a simple form page and set it to be protected, the login form shows but has the fields replaced by the ones on the page I´m trying to protect.

Example page Frontmatter:
```
title: Test
access:
    site.login: true
form:
    name: 'Test Form'
    fields:
        name:
            label: Test
            type: text
    buttons:
        submit:
            type: submit
            value: Submit
```
This makes the page render the "User login" form, but with the "test" input, not the user/password.
