### ISSUE TITLE
replace-default@ not working?

### ISSUE THREAD

**Issue by mncrff** [getgrav/grav-plugin-form#174]
Here is the YAML in my parent blueprint for the field in question:
```
header.visibility:
    type: toggle
    highlight: 1
    options:
        1: 'show'
        0: 'hide'
    default: 1
    validate:
        type: bool
```

And now in my inheriting blueprint:
```
    header.visibility:
        replace-options@: true
        options:
            1: 'test'
            0: 'hide'
        replace-default@: true
            default: 0
```

I am able to replace the options just fine, but for some reason I cannot get the default to change using `replace-default@`. I also tried using the alias `unset-default@` also without success. The documentation states 'You can do the same for individual properties', so does/should this apply to all properties?
