### ISSUE TITLE
Refresh Prevention doesn't work

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-form#190]
I have a form in a modular page, enabled Refresh Prevention Setting in form plugin.
But after submitting the form and Browser Refresh the form gets submitted again?

**Comment by Pyth0ff** [comment]
@axel-rank Could you provide us your yaml frontmatter?

**Comment by axel-rank** [comment]
form:
    name: contact
    action: /
    fields:
        -
            name: name
            label: Name
            classes: form-control
            placeholder: 'Name eingeben'
            type: text
            position: left
            validate:
                required: true
        -
            name: email
            label: Email
            classes: form-control
            placeholder: 'Email Adresse eingeben'
            type: email
            position: left
            validate:
                required: true
        -
            name: message
            label: Nachricht
            placeholder: 'Nachricht schreiben'
            type: textarea
            classes: form-control
            position: right
            validate:
                required: true
    buttons:
        -
            type: submit
            classes: 'btn btn-primary btn-lg'
            value: Senden
    process:
        -
            email:
                from: '{{ form.value.email }}'
                subject: '[Homepage Kontakt von] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            reset: true
        -
            message: 'Vielen Dank für die Nachricht! Ich melde mich so schnell wie möglich.'
cache_enable: false

**Comment by rhukster** [comment]
can you 'paste' that as text.. I really don't feel like retyping that whole thing :)

**Comment by rhukster** [comment]
Ok this works, but needs a little configuration setup.  I've enclosed a zip of a modular page that should be added under a `form` top level page: 

[10.modular.zip](https://github.com/getgrav/grav-plugin-form/files/1306925/10.modular.zip)

The important parts are the `action` and the `display`, they should point to the location of the modular page.

```
---
title: Modular Form

form:
  action: '/form/modular'
  inline_errors: true
  fields:
    person.name:
      type: text
      label: Name
      validate:
        required: true
        
  buttons:
    submit:
      type: submit
      value: Submit
      
  process:
    message: "Thank you from your submission <b>{{ form.value('person.name') }}</b>!"
    reset: true
    display: '/form/modular'  
---

## Modular Form
```

**Comment by rhukster** [comment]
I've updated the docs too.

**Comment by axel-rank** [comment]
- After submitting I want to redirect to the top of my page.
So I have to set action to / 

- I have no modular sub page, my whole page is modular
- I have no /form/modular folder


Here my page structure:
user folder: 01.home

01.home folder:

![bildschirmfoto zu 2017-09-16 10-44-11](https://user-images.githubusercontent.com/12480617/30510821-0d3b78f8-9acc-11e7-88a7-5133718ca3c3.png)

modular.md:
```
---
title: Musik und Gitarrenunterricht im Fichtelgebirge, Bayreuth und Pegnitz
menu: Home
onpage_menu: true
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _header
            - _news
            - _gitarre
            - _musik
            - _pics
            - _uebermich
            - _links
            - _contact
            - _impressum
---
```
**_contact--> form.md:**
```
---
title: Kontakt

form:
    name: contact
    action: '/form/modular'
    fields:
        -
            name: name
            label: Name
            classes: form-control
            placeholder: 'Name eingeben'
            type: text
            position: left
            validate:
                required: true
        -
            name: email
            label: Email
            classes: form-control
            placeholder: 'Email Adresse eingeben'
            type: email
            position: left
            validate:
                required: true
        -
            name: message
            label: Nachricht
            placeholder: 'Nachricht schreiben'
            type: textarea
            classes: form-control
            position: right
            validate:
                required: true
    buttons:
        -
            type: submit
            classes: 'btn btn-primary btn-lg'
            value: Senden
    process:
        -
            email:
                from: '{{ form.value.email }}'
                subject: '[Homepage Kontakt von] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            reset: true
        -
            message: 'Vielen Dank für die Nachricht! Ich melde mich so schnell wie möglich.'
            display: '/form/modular'
cache_enable: false
---

## Kontakt
### Bei Anfragen bitte das Formular ausfüllen! Oder eine E-Mail an: [safe-email]info@axelrank.de[/safe-email]

```
