### ISSUE TITLE
Checkbox validation: The form is being sent although required checkbox is not checked

### ISSUE THREAD

**Issue by macemmek** [getgrav/grav-plugin-form#216]
The form definition:

```
form:
  name: registration-form
  template: form-messages
  fields:
    - name: first_name
      label: First name
      type: text
      validate:
        required: true
    - name: accept_rules
      label: Accept rules
      type: checkbox
      validate:
        required: true
  buttons:
    - type: submit
      value: Send
  process:
    - save:
        fileprefix: registration-
        dateformat: Ymd-His-u
        extension: txt
        body: "{% include 'forms/data.txt.twig' %}"
    - message: Thank you!
```

This is AJAX form. I need to mention that I've set the _novalidate_ attribute on the` <form>` tag because I don't want a browser validation. I utilize own Twig template extending the default one.

```
{% extends "forms/default/form.html.twig" %}

{% block form_classes %}
class="{{ form_outer_classes }} {{ form.classes }}" novalidate
{% endblock %}

{% block inner_markup_buttons_end %}
	</div>
	<div id="form-result"></div>
	<script>
		$(document).ready(function(){
			var form = $('#registration-form');
			form.submit(function(e) {
				// prevent form submission
				e.preventDefault();

				// submit the form via Ajax
				$.ajax({
					url: form.attr('action'),
					type: form.attr('method'),
					dataType: 'html',
					data: form.serialize(),
					success: function(result) {
						// Inject the result in the HTML
						$('#form-result').html(result);
					}
				});
			});
		});
	</script>
{% endblock %}
```

Forms plugin returns validation message related to the text field but talks nothing about the checkbox which is expected to be validated as well:

![validation](https://user-images.githubusercontent.com/513306/33581332-cc756b12-d950-11e7-89f0-e6a32ebde19f.jpg)

On the other hand, when I fill just the first name, the form is sent.
