### ISSUE TITLE
Populating forms fields no longer working with multi-forms

### ISSUE THREAD

**Issue by franei** [getgrav/grav-plugin-form#219]
This seems unrelated to [issue #217](https://github.com/getgrav/grav-plugin-form/issues/217) but I'm pretty sure it's new to v2.11.0:

Pre-populating form fields (in my case a Profile page) with `{% do form.setAllData(grav.user.toArray) %}` no longer works when there are multiple forms.  

This puts the user data into the form fields as expected:

```
{% extends 'partials/base.html.twig' %}

{% do form.setAllData(grav.user.toArray) %}
{% block content %}
	{% include 'forms/form.html.twig' %}
{% endblock %}
```

But this shows empty fields in v2.11.0:
```
{% include 'forms/form.html.twig' with { form: forms('bio') } %}
```

Whereas it works fine with the old `form.php` from v2.10.0.

**Comment by rhukster** [comment]
I will take a look at this today.

**Comment by rhukster** [comment]
I'm trying to recreate this but it's working fine.  I have a custom profile form located in `user/pages/profile/form.md` with:

```yaml
---
title: Profile Form
access:
    site.login: true
    
form:
  name: profile
  fields:
    avatar_img:
      type: avatar
  
    username:
      type: text
      readonly: true
      disabled: true

    email:
      type: email
      placeholder: "Enter your email"
      validate:
        required: true
        message: PLUGIN_LOGIN.EMAIL_VALIDATION_MESSAGE
        
    fullname:
      type: text
      
    title:
      type: text  

    password:
      type: password
      label: Enter new password
      validate:
        message: PLUGIN_LOGIN.PASSWORD_VALIDATION_MESSAGE
        config-pattern@: system.pwd_regex


  buttons:
      -
          type: submit
          value: Submit
      -
          type: reset
          value: Reset

  process:
      update_user: true
      message: "Your profile has been updated"
---

```

Then I have a custom page twig where i'm loading multiple forms:

```twig
{% extends 'partials/base.html.twig' %}

{% block content %}

    {{ content }}
    {% include "forms/form.html.twig" with { form: forms({route:'/form/multiple', name:'form-b'}) } %}

    {% include "forms/form.html.twig" with { form: forms('form-a') } %}

    {% set profile_form = forms('profile') %}
    {% do profile_form.setAllData(grav.user.toArray) %}

    {% include "forms/form.html.twig" with { form: profile_form } %}

{% endblock %}
```

And this works fine.  You referencing a custom profile form called bio? Does this form actually exist and does it have `name: bio`?

**Comment by franei** [comment]
Hi @rhukster,

Yes, the form exists and is named correctly as far as I can tell.

I could reproduce this with a bare-bones Grav install, [here](https://we.tl/6BRmAoIcbh) is a zipped copy in case you want to take a look.

I noticed that you use the regular structure (`form: fields ...`) in your form definition, whereas I use the multi-form structure (`forms: form-name: fields ...`) - could that be the reason why we're getting different results?

See below for my twig code and form. The form itself works fine, and fields are populated as expected when I use the previous version of `form.php`, but not when I use the latest one.



```twig
{% extends 'partials/base.html.twig' %}

{% do form.setAllData(grav.user.toArray) %}

{% block content %}
	 {% include 'partials/messages.html.twig' %}
	 {{ page.content }}
	 {% include 'forms/form.html.twig' with { form: forms('testform') } %}
{% endblock %}
```

```yaml
---
title: Multi-Form-Profile
access:
    site.login: true
forms:
    testform:
        fields:
          avatar_img:
            type: avatar

          username:
            type: text
            readonly: true
            disabled: true

          email:
            type: email
            placeholder: "Enter your email"
            validate:
              required: true
              message: PLUGIN_LOGIN.EMAIL_VALIDATION_MESSAGE

          fullname:
            type: text

          middlename:
            type: text

          title:
            type: text  

          password:
            type: password
            label: Enter new password
            validate:
              message: PLUGIN_LOGIN.PASSWORD_VALIDATION_MESSAGE
              config-pattern@: system.pwd_regex


        buttons:
            -
                type: submit
                value: Submit
            -
                type: reset
                value: Reset

        process:
            update_user: true
            message: "Your profile has been updated"
---
```
