### ISSUE TITLE
Template_format doesn't work (impossible to return json)

### ISSUE THREAD

**Issue by jimblue** [getgrav/grav-plugin-form#221]
For an ajax contact form, I need to access the return data as `json`.

To do so I'm trying to use `form-message.json.twig` by setting `template_format ` to `json` in the page header. Sadly it doesn't seems to work.

https://learn.getgrav.org/content/headers#template-format

Thank you for you help.

PS: comming from #212

**Comment by jimblue** [comment]
Have you been able to reproduce the bug? Do you need more info?

**Comment by rhukster** [comment]
Sorry not gotten chance to look at it.  I think it is a bug though, will mark it as such.

**Comment by jimblue** [comment]
I've just made an other test on a classical website (non modular) with dedicated contact page.

The result is the same `template_format: json` is not working. It always return the content format trough the `html` version of the template...

**Comment by rhukster** [comment]
The template only provides the name.. if you request a `.json` URL it will render with the template + `.json.html`. Alternatively, you can override the extension with `template_format: json` in the page header.

**Comment by jimblue** [comment]
Yes I know @rhukster I am adding `.json` in js

But the solution you told me using `template_format: json` doesn't works, for classic or modular page the result is always html...

**Comment by jimblue** [comment]
I'm using last version of Grav and all plugin, so I think there is a bug with `template_format`

Can you reproduce it?

**Comment by jimblue** [comment]
Hey @rhukster, any update about this bug, `template_format` is still not working.

**Comment by jimblue** [comment]
Some more informations to help you understand the bug:

**The page header:**
```yaml
---
title: Contact
subtitle: 'If you have any questions, please contact me using the form below'
hero: pinkskunkclownfish.jpg
forms:
    contact-form:
        name: contact-form
        template: form-messages
        template_format: json
        classes: validate
        fields:
[...]
---
```
**And the response:**
![screen shot 2018-03-16 at 07 02 57](https://user-images.githubusercontent.com/10623367/37506140-c4295698-28e8-11e8-88f9-434ded46dfef.png)
As you can see it's in `html` format. `Grav` wrongly used `form-message.html.twig` over `form-message.html.json`

**Cheating Grav:**
I've try to cheat `Grav` to understand the bug by replacing the content of `form-message.html.twig` by the content of `form-message.json.twig`.

**Modified `form-message.html.twig`**:
```twig
{% include 'partials/form-messages.json.twig' %}
{% do http_response_code(form.responseCode) %}
```
**And the response:**
![screen shot 2018-03-16 at 07 04 07](https://user-images.githubusercontent.com/10623367/37506266-5816bf12-28e9-11e8-8708-fb0e54d5a17c.png)

This confirm `grav-plugin-form` doesn't respect `template_format` settings in the head.

Thanks for your help!
