### ISSUE TITLE
Dropzone isn't working and mail attachment isn't sent

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-form#225]
Here is my form definition:
```yaml
form:
    name: form_10
    template: form-messages
    refresh_prevention: true
    id: form_10
    fields:
        name:
            label: Имя
            placeholder: Ваше имя *
            autocomplete: 'off'
            id: form10_name
            type: text
            validate:
                required: true

        email:
            label: E-mail
            id: form10_email
            type: email
            placeholder: 'Ваш e-mail *'
            autocomplete: 'off'
            validate:
                rule: email
                required: true

        message:
            label: Сообщение
            id: form10_message
            type: textarea
            placeholder: 'Текст сообщения *'
            autocomplete: 'off'
            validate:
                required: true

        custom_file:
            type: file
            label: Прикрепить файл
            multiple: false
            destination: '@self'
            random_name: false
            avoid_overwriting: false
            limit: 15
            accept:
                - '*'

        honeypot:
            type: honeypot

    buttons:
        - type: submit
          classes: 'btn_style1 btn_small btn_left_relative btn_sendCall_2'    
          value: Заказать

    process:
        - email:
            from: "{{ config.plugins.email.from }}"
            to:
              - "{{ config.plugins.email.to }}"
            subject: "[mezin.me] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
            attachments: [custom_file]
            #    - 'custom_file'
            subject: "Сообщение от {{ form.value.name|e }} [Site]"
        - message: 'Ваше сообщение успешно отправлено!<br>Оставайтесь на связи.'
```

I see dropzone file area:
![image](https://user-images.githubusercontent.com/7556290/34207228-a8b03724-e59a-11e7-85d6-573e91d7e17a.png)
But it isn't working by click or by drag&drop files. Nothing. 
No errors in console etc... 

Ok. Let's disable built in css in Form plugin options:
![image](https://user-images.githubusercontent.com/7556290/34207291-e7bf7eca-e59a-11e7-9a88-947bc3395a5c.png)
Now we can select file but input not changed and I see no file in `@self` (where md) directory.

Finally no attachments to my email.

How to fix?
