### ISSUE TITLE
error when submitting a form with recaptcha

### ISSUE THREAD

**Issue by manuel-84** [getgrav/grav-plugin-form#228]
plugin v2.11.1 - Grav v1.3.10

/user/plugins/form/classes/form.php : 628
error: "key() expects parameter 1 to be array, string given"

`$action = \key($data);`
arguments: "captcha"

my form:

```
form:
    name: contatto
    fields:
        -
            name: nome
            label: 'Nome e Cognome'
            placeholder: 'Nome e Cognome'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: email
            label: 'Indirizzo E-Mail'
            placeholder: 'Indirizzo E-Mail'
            type: email
            validate:
                required: true
        -
            name: messaggio
            label: Messaggio
            placeholder: Messaggio
            type: textarea
            validate:
                required: true
        -
            name: g-recaptcha-response
            type: captcha
            label: 'Verifica antispam'
            recaptcha_not_validated: 'Captcha non valida!'
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Invia
    process:
        - captcha
        -
            email:
                subject: '[Email di contatto da XXX] {{ form.value.nome|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: contatto-
                dateformat: d-m-Y-H.i.s-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Grazie per averci contattato!'
        -
            display: thankyou
```
