### ISSUE TITLE
test new RC, it seems classes in form not taking into account

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav-plugin-form#232]
Hi 
just test new RC, it seems `classes` in form not taking into account.

Excerpt from my `form.html.twig` and the `frontmatter`

````
form:
    name: contact
    classes: my-custom-classe
    action: /contact
````
`form_outer_classes` works no issue from theme `onTwigInitialized`

````
<form name="{{ form.name }}"
      action="{{ action | trim('/', 'right') }}"
      method="{{ method }}"{{ multipart }}
      {% if form.id %}id="{{ form.id }}"{% endif %}
      {% block form_classes %}
      class="{{ form_outer_classes }} {{ form.classes }}"
      {% endblock %}
      {% if form.novalidate %}novalidate{% endif %}
>
````

`Grav v1.4.0-rc.1`
`Admin v1.7.0-rc.2`
`Form v2.11.2`
