### ISSUE TITLE
How to avoid spam in contact forms?

### ISSUE THREAD

**Issue by Sergiop79** [getgrav/grav-plugin-form#237]
Hello, I have two contact forms in a site. I implemented 2 honeypot fields and googles recaptcha and still receiving spam. The forms submission is via Ajax.

form in homepage (modular)

```yaml
form:
    action: /
    name: home-contact-form
    classes: home-contact-form
    template: form-messages
    referesh_prevention: true
    fields:
        -
            name: name
            label: Nombre
            type: text
            validate:
                required: true
        -
            name: email
            label: Email
            type: email
            validate:
                required: true
        -
            name: company
            label: Empresa
            type: text
        -
            name: phone
            label: Teléfono
            type: text
        -
            name: message
            label: Mensaje
            type: textarea
            validate:
                required: true
        -
            name: g-recaptcha-response
            label: Captcha
            type: captcha
            recaptcha_site_key: MY_SITE_KEY
            recaptcha_not_validated: 'Captcha no válido'
            validate:
                required: true
        -
            name: web
            type: honeypot
        -
            name: paraosos
            type: honeypot
    buttons:
        submit:
            id: submit
            type: submit
            value: 'Me interesa trabajar juntos'
    process:
        -
            captcha:
                recaptcha_secret: MY_SECRET_KEY
        -
            message: 'Muchas gracias {{ form.value.name }} por contactar con nosotros. Hemos recibido tu correo y nos pondremos en contacto contigo con la mayor rapidez posible. Te enviamos una copia del correo que nos has enviado para que lo tengas como referencia. Si parece que no lo has recibido, revisa tu bandeja de correo no deseado.'
        -
            email:
                subject: 'Nueva solicitud de contacto desde la web'
                from: '{{ config.plugins.email.from }}'
                to: ['{{ config.plugins.email.from }}']
                body: '<p>Nueva solicitud de contacto desde la web</p>{% include ''forms/data.html.twig'' %}'
        -
            email:
                subject: 'dr.Minsky | mensaje de contacto'
                from: '{{ config.plugins.email.from }}'
                to: ['{{ form.value.email }}']
                body: '<p>Muchas gracias por su solicitud. Le responderemos con la mayor rapidez posible.</p> <br><br> {% include ''forms/data.html.twig'' %}'
```

Second form in contact page (static)

```yaml
form:
    name: contact-form
    classes: contact__form
    template: form-messages
    referesh_prevention: true
    fields:
        -
            name: name
            label: Nombre
            type: text
            validate:
                required: true
        -
            name: email
            label: Email
            type: email
            validate:
                required: true
        -
            name: company
            label: Empresa
            type: text
            validate:
                required: false
        -
            name: phone
            label: Teléfono
            type: text
            validate:
                required: false
        -
            name: message
            label: Mensaje
            type: textarea
            validate:
                required: true
        -
            name: g-recaptcha-response
            label: Captcha
            type: captcha
            recaptcha_site_key: MY_SITE_KEY
            recaptcha_not_validated: 'Captcha no válido'
            validate:
                required: true
        -
            name: web
            type: honeypot
        -
            name: paraosos
            type: honeypot
    buttons:
        -
            id: submit
            type: submit
            value: Enviar
    process:
        -
            captcha:
                recaptcha_secret:  MY_SECRET_KEY
        -
            message: 'Muchas gracias {{ form.value.name }} por contactar con nosotros. Hemos recibido tu correo y nos pondremos en contacto contigo con la mayor rapidez posible. Te enviamos una copia del correo que nos has enviado para que lo tengas como referencia. Si parece que no lo has recibido, revisa tu bandeja de correo no deseado.'
        -
            email:
                subject: 'Nueva solicitud de contacto desde la web'
                from: '{{ config.plugins.email.from }}'
                to: ['{{ config.plugins.email.from }}']
                body: '<p>Nueva solicitud de contacto desde la web</p>{% include ''forms/data.html.twig'' %}'
        -
            email:
                subject: 'dr.Minsky | mensaje de contacto'
                from: '{{ config.plugins.email.from }}'
                to: ['{{ form.value.email }}']
                body: '<p>Muchas gracias por su solicitud. Le responderemos con la mayor rapidez posible.</p> <br><br> {% include ''forms/data.html.twig'' %}'
```

The submission of both forms is via ajax, and im using jquery validate https://jqueryvalidation.org/  to validation, with the next script

```javascript
$(function() {
	        $('#home-contact-form').validate({
	            rules: {
	                'data[name]': 'required',
	                'data[email]': {
	                    required: true,
	                    email: true
	                },
	                'data[message]': 'required'
	            },

	            messages: {
	                'data[name]': 'Por favor indica tu nombre',
	                'data[email]': 'Por favor indica una dirección de email válida',
	                'data[message]': 'Por favor añade un mensaje'
	            },

	            submitHandler: function (form) {
					if (grecaptcha.getResponse() === '') {
						alert('Debes rellenar el Captcha');
						return false;
					}

					var $submitBtn = $('#submit');
	                $submitBtn.attr('disabled', 'disabled');
	                
	                $('#form-result').html('<div class="loader">Enviando...</div>');



	                $.ajax({
	                    url: form.action,
	                    type: form.method,
	                    dataType: 'html',
	                    data: $(form).serialize(),
	                    success: function (result) {
	                        $submitBtn.removeAttr('disabled');
	                        $('#form-result').html(result);
	                        $('#home-contact-form').trigger('reset');
	                    }
	                });

	                return false;                
	            }
	        });

	        // Show hide contact form
	        var $contactCloseBtn = $('#home-contact-close-btn');
	        var $heroCta = $('.hero__cta');

	        var $contactWindow = $('#home-contact');

	        var toggleContact = function (e) {
	        	e.preventDefault();
	        	$contactWindow.toggleClass('open');
	        };

	        $contactCloseBtn.on('click', toggleContact);
	        $heroCta.on('click', toggleContact);
	    });
```

Is there another method to block spam in forms?
The versions are: Grav v1.3.10 - Admin v1.6.7

Thanks
