### ISSUE TITLE
autocomplete attributes not shown on form rendered

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-form#242]
Hi guys,

trying to figure out how to add the custom form attributes using a simple frontmatter
![captura de ecran din 2018 03 04 la 12 31 15](https://user-images.githubusercontent.com/7076631/36945547-fab49ec4-1fa7-11e8-9c41-043a1dc87e53.png)

``` 
  fields:

        - name: name
          id: name
          label: Name
          classes: input
          placeholder: Enter your name
          attributes: 
            autocomplete: name
          style: fancy
          type: text
          validate:
            required: true
```
but the `attributes` renders as plain ` ='' `
is this something that can be considered a bug ? or my way of declaring it is not proper ?

**Comment by rhukster** [comment]
Should just be:

```
  fields:

        - name: name
          id: name
          label: Name
          classes: input
          placeholder: Enter your name
          autocomplete: on
          style: fancy
          type: text
          validate:
            required: true
```
