### ISSUE TITLE
Form - File upload error

### ISSUE THREAD

**Issue by aetherspacemind** [getgrav/grav-plugin-form#247]
Hey, I got an error here. When I upload a file in the drag and drop, and I hover over the thumbnail I get a little red box that pops under the thumb that says "Undefined Index: Data". Also, my attachment wont send. I have this in my .md 
```yaml
        -
            name: fieldName
            label: 'The Label'
            type: file
            outerclasses: 'myOuterClass'
            multiple: true
            limit: 4
            destination: '@self'
            accept:
                - 'image/*'
            avoid_overwriting: true
            autofocus: false
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to:
                    - '{{ config.plugins.email.from }}'
                subject: 'My Lovely Form {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
                attachments:
                    - fieldName
```
------------------------------------------------
error.log

[[2018-04-18 11:33:52] grav.CRITICAL: Undefined index: data - Trace: #0 /home/noneedtoknow/public_html/user/plugins/form/classes/Form.php(396): Whoops\Run->handleError(8, 'Undefined index...', '/home/noneedtoknow...', 396, Array) #1 /home/noneedtoknow/public_html/user/plugins/form/form.php(189): Grav\Plugin\Form\Form->uploadFiles() #2 [internal function]: Grav\Plugin\FormPlugin->onPageInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 /home/noneedtoknow/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #4 /home/noneedtoknow/public_html/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #5 /home/noneedtoknow/public_html/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #6 /home/noneedtoknow/public_html/system/src/Grav/Common/Grav.php(283): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #7 /home/noneedtoknow/public_html/system/src/Grav/Common/Processors/PagesProcessor.php(26): Grav\Common\Grav->fireEvent('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #8 /home/noneedtoknow/public_html/system/src/Grav/Common/Grav.php(132): Grav\Common\Processors\PagesProcessor->process() #9 /home/noneedtoknow/public_html/system/src/Grav/Common/Grav.php(374): Grav\Common\Grav->Grav\Common\{closure}() #10 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('pages', 'Pages', Object(Closure)) #11 /home/noneedtoknow/public_html/system/src/Grav/Common/Grav.php(350): call_user_func_array(Object(Closure), Array) #12 /home/noneedtoknow/public_html/system/src/Grav/Common/Grav.php(133): Grav\Common\Grav->__call('measureTime', Array) #13 /home/noneedtoknow/public_html/index.php(52): Grav\Common\Grav->process() #14 {main} [] []
