### ISSUE TITLE
Allow for multiple buttons

### ISSUE THREAD

**Issue by finanalyst** [getgrav/grav-plugin-form#251]
Unless documented elsewhere and I missed it, the `Form` plugin only _really_ allows for a single `submit` button and a `reset` button. 

It is possible to set a `task: mything` attribute to a button, and the POST data contains `task=>mything` if the button is clicked.

However, the `Form` plugin does not trap this extra information.

I suggest enhancing the plugin to send information to `onFormsProcessed` about non-standard buttons.

**Comment by rhukster** [comment]
You can certainly add extra buttons, and you can provide tasks.. eg.

```
buttons:
   submit:
     value: Submit
   my-button:
      type: button
      task: my-task
      value: My Task
```

https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/fields/checkbox/checkbox.html.twig
