### ISSUE TITLE
single checkboxes are not rendered in data.html.twig

### ISSUE THREAD

**Issue by sebastianbaumann** [getgrav/grav-plugin-form#262]
Like I mentioned in another issue, something seems broken with the `checkbox.html.twig` template.
I define checkbox fields like this in my `form.md`

```
beratung:
  type: checkbox
  outerclasses: px1 w12 mb1
  label: "Beratung vor Ort"
```
But when sending the email, they will not appear in the email body.
