### ISSUE TITLE
Forms timeout with session

### ISSUE THREAD

**Issue by marshmn** [getgrav/grav-plugin-form#275]
If you view a page with a form on it, and then wait for the PHP session to time-out, the form will no longer work. Hitting the submit button will present an error such as: "Oops there was a problem, please check your input and submit the form again."

One suggestion on potentially how to fix this from @rhukster is that perhaps there should be an AJAX ping to keep the session alive.

**Comment by marshmn** [comment]
Having thought about this some more, I'm not convinced that an AJAX ping is necessarily the right way to go for all usage scenarios.

I would definitely fix some cases and be an improvement, but it does have a side effect of keeping more active PHP sessions open presumably - which might not be a good thing if you're wanting to keep some control on how long users are logged in for etc.

It will also fail to solve the problem in scenarios where, for example, you are using a laptop to view a page with a form on it, then suspend your laptop and wake it hours later. The AJAX ping clearly won't have been in effect during that time so now filling the form will fail.

I wonder if it would be better to have an option on a form-by-form basis to set whether or not it should care about whether there is an active session?

**Comment by rhukster** [comment]
I need to think about this to see if there's a solution.

**Comment by mahagr** [comment]
This has been implemented in Form 3.0, though it needs to be documented.

**Comment by skyleo** [comment]
Is it possible to get the fix for that as a diff for the current stable version of Grav?
Or will we have to wait for Grav 3.0?
Any other kludges I can use meanwhile?

**Comment by Sogl** [comment]
@mahagr This problem still exists in Form 3.0.2
Problem with modular form when form send I see "Oops, you have a problem"... `cache_enable: false` is set

**Comment by mahagr** [comment]
For logged in users you can try:

```
form:
    name: my-form
    remember_state: user
    uniqueid: asdf1234
    id: my-form
```

**Comment by Sogl** [comment]
I don't use auth mechanism, just contact form with name, email, phone.

**Comment by rhukster** [comment]
Are you using:

```
form:
  keep_alive: true
...
```

???

**Comment by rhukster** [comment]
I set my session timeout to 30 secs and reloaded my form, and keep alive seems to be working just fine.

![Image 2019-05-06 at 5 45 19 PM](https://user-images.githubusercontent.com/1084697/57261821-be94c600-7026-11e9-86f4-ce0a7fb83ac0.png)

**Comment by Sogl** [comment]
@rhukster Just added `keep_alive: true` to my form without success.
This is GH problem that it not add reference from `CHANGELOG.md`:
![image](https://user-images.githubusercontent.com/7556290/57297636-c4e37a80-70d8-11e9-9af9-b8a9e86d742e.png)

Ok, I give more info.
My filesystem:
![image](https://user-images.githubusercontent.com/7556290/57297688-f52b1900-70d8-11e9-82f3-b87b0e411e21.png)

Full `home.md` content:
```yaml
---
title: Юрист Евгений Имангулов
body_classes: title-center title-h1h2
cache_enable: false
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _intro
            - _area
            - _digits
            #- _about
            - _advantages
            - _record
            - _contact

form:
    keep_alive: true
    name: send-form
    action: /home
    template: form-messages
    refresh_prevention: true

    fields:
        name:
            label: Имя
            display_label: false
            placeholder: Ваше имя
            classes: 'form-control form-control-lg'
            type: text
            validate:
                required: true

        phone:
            label: Телефон
            display_label: false
            type: text
            classes: 'phone form-control form-control-lg'
            placeholder: 'Ваш телефон'
            autocomplete: true
            validate:
                required: true
                pattern: '^((\+?7|8)[ \-]?)?((\(\d{3}\))|(\d{3}))?([ \-])?(\d{3}[\- ]?\d{2}[\- ]?\d{2})$'
                message: 'Формат: +7 (***) ***-**-**'

        question:
            label: Вопрос
            display_label: false
            placeholder: Ваш вопрос на консультацию
            classes: 'form-control form-control-lg'
            type: text
            validate:
                required: true


        honeypot:
            type: honeypot

    buttons:
        submit:
            type: submit
            classes: 'btn-one btn-square'
            value: Отправить

    process:
        email:
            from: "{{ config.plugins.email.from }}"
            to:
                - "{{ config.plugins.email.to }}"
            subject: "Заказ консультации от {{ form.value.name|e }} [imangulow.ru]"
            body: "{% include 'forms/data.html.twig' %}"
        message: 'Спасибо! Я обязательно свяжусь с вами.'
---
```

AJAX part in js file:
```js
$(document).ready(function() {
...
   var form = $('#send-form');
   form.submit(function(e) {
        // prevent form submission
        e.preventDefault();

        var record = $('#record');

        // submit the form via Ajax
        $.ajax({
            url: form.attr('action'),
            type: form.attr('method'),
            dataType: 'html',
            data: form.serialize(),
            success: function(result, status, jqXHR) {

                console.log(result);
                console.log(status);
                console.log(jqXHR);

                if ( $( result ).hasClass( "alert-success" ) ) {
                    form.addClass('d-none');
                }

                record.find(".alertbox").html(result);
                record.find(".alertbox").removeClass("d-none");
           }
       });
   });
...
});
```

Grav 1.6.8 and all plugins is up to date:
![image](https://user-images.githubusercontent.com/7556290/57298375-b8f8b800-70da-11e9-9d53-ebe3db7524a1.png)

You can also check the problem here on my site:
https://imangulow.ru/#record

The form does not work until I clear the cache.
