### ISSUE TITLE
Every message in notice is green in AJAX form

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-form#286]
Hello!

`console.log(result);` in Ajax success show me: `<div class="alert notices green">Thank you!</div>` and `<div class="alert notices green">Form submitted twice</div>`with green notice, but in the second case it should be red.

I use modular page. And set form in `home.md`:
![image](https://user-images.githubusercontent.com/7556290/47313472-b3a8b400-d647-11e8-9c24-208abbd93826.png)

My form:
```yaml
form:
    name: send-form
    action: /home
    template: form-messages
    refresh_prevention: true

    fields:
        name:
            label: Name
            display_label: false
            placeholder: Your name
            classes: 'form-control form-control-lg'
            type: text
            validate:
                required: true

        phone:
            label: Phone
            display_label: false
            type: text
            classes: 'phone form-control form-control-lg'
            placeholder: 'Your phone'
            autocomplete: true
            validate:
                required: true
                pattern: '^((\+?7|8)[ \-]?)?((\(\d{3}\))|(\d{3}))?([ \-])?(\d{3}[\- ]?\d{2}[\- ]?\d{2})$'
                message: 'Формат: +7 (***) ***-**-**'

        question:
            label: Question
            display_label: false
            placeholder: Your question
            classes: 'form-control form-control-lg'
            type: text
            validate:
                required: true


        honeypot:
            type: honeypot

    buttons:
        submit:
            type: submit
            classes: 'btn-one btn-square'
            value: Send

    process:
        email:
            from: "{{ config.plugins.email.from }}"
            to:
                - "{{ config.plugins.email.to }}"
                #  - "{{ form.value.email }}"
            subject: "Consultation from {{ form.value.name|e }} [site.com]"
            body: "{% include 'forms/data.html.twig' %}"
        message: 'Thx!'
```

My js:
```js
var form = $('#send-form');
form.submit(function(e) {
     // prevent form submission
     e.preventDefault();

     var record = $('#record');

     // submit the form via Ajax
     $.ajax({
         url: form.attr('action'),
         type: form.attr('method'),
         dataType: 'html',
         data: form.serialize(),
         success: function(result, status, jqXHR) {

             console.log(result);
             console.log(status);
             console.log(jqXHR);

              if ( $( result ).hasClass( "green" ) ) {
                  form.addClass('d-none');
              }

             record.find(".alertbox").html(result);
             record.find(".alertbox").removeClass("d-none");
        }
    });
});

```
