### ISSUE TITLE
File upload, file is always stored though stopPropagation

### ISSUE THREAD

**Issue by horver** [getgrav/grav-plugin-form#287]
Hello!

I want to upload a file with password protection. The docs said:

>  Every time a file is added to the field, it's automatically uploaded to a temporary folder, and will only be stored when the Save (or Submit) action takes place.

So I tried with this:
The `form.md`:
```yaml
form:
    name: uploader-form
    fields:
      
      ...other fields like password, name, etc,....
        -   name: myfile
            type: file
            destination: 'user/plugins/myplugin/uploads'
           
    buttons:
        -   type: submit
            value: Upload
    process:
        -   uploadFile:
        -   save:
        -   message: 'Uploaded!'
        -   reset: true
```

And I made a plugin, with an `onFormProcessed` event hook:
```php
public function onFormProcessed(Event $event)
    {
        $form = $event['form'];
        $action = $event['action'];
        $params = $event['params'];
   
        $post = isset($_POST['data']) ? $_POST['data'] : [];
        $pass = $post['password'];

        switch ($action) {
            case 'uploadFile':
                if (sha1($pass) != 'myhash')  {
                    $this->grav->fireEvent('onFormValidationError', new Event([
                        'form'    => $event['form'],
                        'message' => 'Bad password'
                    ]));
 
                    $event->stopPropagation();
                    return;
                }
        }
    }
```

The `$event->stopPropagation();` seems working, when the password is correct: I got the `Uploaded` message and the form reset as well. Also with a bad password the validation error shows up, and the processes are stopped: I don't get the message and the reset.
But the file is always stored in the destination.

I don't know it is  a bug or I'm doing something wrong?

**Comment by rhukster** [comment]
The upload is actually handled by an ajax request from the dropzone element in the upload field.  So this is uploaded to a temporary location. Then during the save, uploaded files are moved to the final location.  

The `onFormProcessed()` event is called after this file uploading/moving process has been complete.

**Comment by rhukster** [comment]
BTW, you can see this for yourself in the `Form::post()` method.

**Comment by mahagr** [comment]
This has been fixed in the upcoming Form 3.0 with two options:

Use the default upload logic:
```yaml
    process:
        - uploadFile:
        - upload: true
        - save:
        - message: 'Uploaded!'
        - reset: true
```

Do the file upload yourself inside uploadFile:
```yaml
    process:
        - upload: false
        - uploadFile:
        - save:
        - message: 'Uploaded!'
        - reset: true
```
