### ISSUE TITLE
Modular form not redirecting to thankyou page and not sending email.

### ISSUE THREAD

**Issue by bnjroos** [getgrav/grav-plugin-form#288]
Hi,

MY code was working properly before but something seems broken.
When submitting the form, I just get redirected to /home, the email is not sent and the thankyou page is not displayed .
If I remove the `action: /home` field it will return an error 400 but will send the email. If I try to create a form page with the exact same code it will work and display the thankyou page.

Here is my modular.en.md :

```
---
title: mywebsite.io
menu: Home
form:
    name: my-nice-form
    action: /home
    fields:
        -
            name: name
            id: name
            label: Name
            classes: 'form-control form-control-lg'
            placeholder: 'Enter your name'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: email
            id: email
            classes: 'form-control form-control-lg'
            label: Email
            placeholder: 'Enter your email address'
            type: text
            validate:
                rule: email
                required: true
        -
            name: phone
            id: phone
            label: Phone
            classes: 'form-control form-control-lg'
            placeholder: 'Enter your Phone'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: company
            id: company
            label: Company
            classes: 'form-control form-control-lg'
            placeholder: 'Enter your Company'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: city
            id: city
            label: City
            classes: 'form-control form-control-lg'
            placeholder: 'Enter your City'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: country
            id: country
            label: Country
            classes: 'form-control form-control-lg'
            placeholder: 'Enter your Country'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: message
            label: Message
            classes: 'form-control form-control-lg'
            size: long
            placeholder: 'Enter your message'
            type: textarea
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Submit
            class: 'btn btn-primary btn-block'
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: ['{{ config.plugins.email.from }}', '{{ form.value.email }}']
                subject: '[Feedback] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Thank you for your interest in our products!'
        -
            display: thankyou
onpage_menu: true
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _intro
            - _features
            - _app
            - _video
            - _testimonials
            - _text
            - _news
            - _contact
---
```

My contact form.md:
```
---
hidemenu: false
title: Contact
cahe_enable: false
---
### Let us know your interest {.text-center .m-b-lg}
```

Any idea of what could be wrong ?

Thank you in advance,

Bnjroos
