### ISSUE TITLE
validate: { rule: foo } not working for subfields?

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav-plugin-form#297]
Sample:

```yaml
rules:
  email:
    type: email
    pattern: "^\w([\w\.+-]*[\w-])?@([\w-]+\.)+[a-z]{2,5}$"
    required: true
  name:
    pattern: "^.{2,40}$"
    required: true

form:
  fields:
    first-last-name:
      type: fieldset
      fields:
        firstName:
          validate:
            rule: name
        lastName:
          validate:
            rule: name
    email:
      type: email
      validate:
        rule: email
```

No `rule` seem to apply for `firstName` / `lastName` subfields.
