### ISSUE TITLE
Problem with select field when multiple: true

### ISSUE THREAD

**Issue by KasperMadsen** [getgrav/grav-plugin-form#315]
Hey,
I have configured the form shown below. It should simply send a mail with all content when submitted, but it doesn't work for the select field when multiple:true. If I set multiple:false, then it works perfectly fine.

Is there anything I am missing?

Thanks :)

Best,
Kasper

```
title: Opret
cache_enable: false
process:
    markdown: true
    twig: true
form:
    name: contact
    fields:
        -
            name: name
            label: 'Navn på Forening/Klasse + Skole/Firma'
            placeholder: 'Skriv navn her'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: booking-resource
            label: 'Vælg resourcer der skal bookes'
            type: select
            multiple: true
            options:
                friluftsbad: Friluftsbad
                volleybane: Volleybane
                petanque: Petanque
                bordebaenke: 'Borde og Bænke'
                grill: Grill
                basket: Basketbane
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Send
        -
            type: reset
            value: Nulstil
    process:
        -
            email:
                subject: '[Hjemmeside bookingformular] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            display: thankyou
```
