### ISSUE TITLE
Issue with `type: file` when nested into lists and fieldsets

### ISSUE THREAD

**Issue by ricardo118** [getgrav/grav-plugin-form#322]
assuming a blueprint similar to
```
header.sections:
    // this is a list
      .subsections:
         // another list here where .image is a part of
         .image:
           type: fieldset
           fields:
              .image.file:
                  type: file
                  destination: some-folder
```

the header.sections.subsections.image.file doesn't get picked up by the blueprints which then causes a `destination not found` error when attempting to upload.

Ive spoken to @mahagr regarding this 
![slice1](https://user-images.githubusercontent.com/7531933/51991836-d8f95980-24a3-11e9-8dcc-f6b0dc473ea0.png)

**Comment by ganar** [comment]
I can confirm that this is also failing on my website: file seems to be added and uploaded but it is nowhere to be found in the server

**Comment by rhukster** [comment]
Have you tried this with latest 1.6RC and forms 3.0RC?  Things have changed a fair bit with file field.

**Comment by ganar** [comment]
I just did: it does work with  latest 1.6RC and forms 3.0RC. A number of other issues has been solved with this one, not just the uploads.

This is beta code: do you have an estimate on when will we be able to use this code in production?

**Comment by rhukster** [comment]
It’s actually RC = release candidate.  It should be used for testing and development. 

I’m just trying to get a bit more documentation done but it’s functionally complete.

**Comment by ganar** [comment]
Solved! thanks a lot @rhukster !

**Comment by vilmarzti** [comment]
Hello,

This problem seems to have resurfaced. I also get an `destination not specified error` with the following blueprint:
```
title: Title
'@extends':
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          unset@: true
        costum:
          ordering@: -10
          type: tab
          title: List-items
          fields:
           header.picture_select:
              type: list
              style: vertical
              label: Liste mit Selektion
              classes: field-selection
              fields:
                .slider:
                  type: fieldset
                  title: Slider images
                  fields:
                    .slider.image1:
                      type: file
                      label: linkes Bild
                      destination: '@self'
                      accept: 
                        - 'image/*'
```
I also posted on the [forum](https://discourse.getgrav.org/t/destination-not-found-error-even-though-destination-is-set/11017) if that of is any help.

Steps to reproduce:
* Start with a fresh install of 16.19 or 1.7.0-rc (Forms 4.0.1)
* Create a blueprint called test.yaml with code from above as content
* In the admin panel create a new page from the blueprint
* Save the page
* Try to upload an image, which leads to the `destination not specified` error
