### ISSUE TITLE
operation: add not working

### ISSUE THREAD

**Issue by ghtmtt** [getgrav/grav-plugin-form#324]
Hi guys,

I have a simple form with  the following saving options:

```
        - save:
            fileprefix: iscrizione-
            dateformat: Ymd-His-u
            extension: txt
            operation: add
            body: "{% include 'forms/data.txt.twig' %}"
```
but instead to add each new entry to the existing file the plugin is always creating new files. Am I missing something? 

Thanks
