### ISSUE TITLE
The problem of sending with multiple forms.

### ISSUE THREAD

**Issue by k1ll1n** [getgrav/grav-plugin-form#327]
my forms in index.md
```yaml
forms:
    request_form:
        name: request_form
        classes: request
        method: POST
        fields:
            - name: name
              type: text
              validate:
                required: true
            - name: email
              type: text
              validate:
                rule: email
                required: true
        buttons:
                - type: submit
                  value: Оставить заявку
                  classes: submit
        process:
            - email:
                from: "{{ config.plugins.email.from }}"
                to:
                  - "{{ config.plugins.email.from }}"
                  - "{{ form.value.email }}"
                subject: "[Feedback] {{ form.value.name|e }}"
                body: "{% include 'forms/data.html.twig' %}"
            - save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: "{% include 'forms/data.txt.twig' %}"
```

my template for this form
```html
<div class="request-overlay" aria-hidden="true">
    <form name="{{ form.name }}" method="{{ form.method }}" {% if form.id %}id="{{ form.id }}"{% endif %} class="{{ form.classes }}" action="{{ action | trim('/', 'right') }}">
        <h2>задать вопрос врачу</h2>
        <p>Чтобы записаться на приём, оставьте<br>свои данные и наш администратор свяжется<br>с вами для уточнения вопросов.</p>
        <div>
            <input placeholder="Ваше имя*" name="name" required>
            <input placeholder="Ваше e-mail*" name="email" required>
        </div>
        <input class="accept" type="checkbox" id="accept-request" name="accept" value="true" required>
        <label for="accept-request"><a><span>Оставляя свои контактные данные, вы подтверждаете свое совершеннолетие, соглашаетесь на обработку персональных данных в соответствии с правовой информацией.</span></a></label>
        <input type="submit" value="Оставить заявку">

        {% include 'forms/fields/uniqueid/uniqueid.html.twig' %}
        {{ nonce_field('form', 'form-nonce')|raw }}
    </form>
</div>
```

Inclusion of this form in the main template

```
{% include "forms/request_form.html.twig" with { form: forms('request_form') } %}
```
The form is displayed normally, but the data from the form is not saved or sent.
If I change the plural forms to single ones, then everything starts working. Data is saved and sent.
Same single form
```yaml
form:
    name: request_form
    classes: request
    method: POST
    fields:
        - name: name
          type: text
          validate:
            required: true
        - name: email
          type: text
          validate:
            rule: email
            required: true
    buttons:
            - type: submit
              value: Оставить заявку
              classes: submit
    process:
        - email:
            from: "{{ config.plugins.email.from }}"
            to:
              - "{{ config.plugins.email.from }}"
              - "{{ form.value.email }}"
            subject: "[Feedback] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
        - save:
            fileprefix: feedback-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
```

But I need precisely the plural forms, since then I am going to add one more form here.

What else do I need to override from the standard form template so that my template starts working. I ask this because if I use a standard template for my plural forms, they start working.
