### ISSUE TITLE
recaptcha not working in forms GRAV

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav-plugin-form#334]
Hello all
i have form in standart Grav fields
```
---
title: 'Сайты под ключ в Краснодаре'
action: '@self'
cache_enable: false
form:
    name: my-nice-form
    fields:
        -
            name: name
            placeholder: 'Имя'
            autocomplete: 'on'
            type: text
            classes: 'form-control inp'
            validate:
                required: true
        -
            name: email
            placeholder: 'Email'
            type: text
            classes: 'form-control inp'
            validate:
                rule: email
                required: true
        -        
           name: g-recaptcha-response
           label: Captcha
           type: captcha
           recaptcha_site_key: ////////
           recaptcha_not_validated: 'Captcha not valid!'
           validate:
                required: true
    buttons:
        -
            type: submit
            value: Рассчитать
            classes: 'btn danger-color w100'
    process:
        -
            email:
                from: '{{ form.value.email|e }}'
                to: '{{ config.plugins.email.to }}'
                subject: 'Contact by {{ form.value.name|e }}'
                body: "{% include 'forms/data.html.twig' %}"
        - 
           captcha:
                recaptcha_secret: ///////
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
---
```
but this not work
e-mail's sent without captcha validation
whats wrong?
sorry me english bad...)))

**Comment by abooks23** [comment]
not modular

**Comment by abooks23** [comment]
lot of error my be associated with loading other part of page via ajax... but all need js loaded !

**Comment by rhukster** [comment]
I can't replicate this on my side.. recapatcha is working fine.  I suggest putting the captcha key/secret i your `user/config/plugins/form.yaml` and removing them from the page form.. this should make a difference, but just better practice.  My test form looks like this:

```yaml
---
title: 'reCAPTCHA Form'

forms:
    someform:
        fields:
            form-message:
                label: Body
                rows: 10
                placeholder: 'Enter your message here'
                autofocus: true
                type: textarea
            g-recaptcha-response:
                label: Captcha
                type: captcha
                recaptcha_not_validated: 'Captcha not valid!'
    
        buttons:
            submit:
                type: submit
                value: Submit
                
        process:
            captcha: true
            message: 'Successfully passed reCAPTCHA!'
    
---
```

**Comment by rhukster** [comment]
Also, what does your form config look like? New version of Form has several versions.. `2-checkbox` is default, but there's also `2-invisible` and `3`.

```
recaptcha:
  version: 2-checkbox
  site_key: xxxxxxxxxxxxxxx
  secret_key: xxxxxxxxxxxxxxx
```
