### ISSUE TITLE
Duplicated error messages with inline errors

### ISSUE THREAD

**Issue by nr12157** [getgrav/grav-plugin-form#337]
Running Grav 1.6.6 and Form 3.0.1. 

When you have an input field in your form with multiple validations (e.g. a pattern and required), if you have inline errors enabled, when the form is submitted and there is an error, the returned message is replicated to match the number of validation rules. So for the code below, if the user leaves the email field blank, there is an error message because the input wasn't an email, but also an error message because there wasn't anything input into the field.

FYI `client_side_validation` is set to false.

```
            name: email
            label: Email
            placeholder: 'Enter your email address'
            type: email
            validate:
                required: true
                message: "Please enter a valid email address!"
```
