### ISSUE TITLE
Form success message not showing

### ISSUE THREAD

**Issue by marshmn** [getgrav/grav-plugin-form#340]
Since upgrading Grav from 1.6.3 to 1.6.8, the success message from my form no longer appears.

I have the following form defined on my (one-page) site:

```yaml
form:
    name: contact
    action: /
    client_side_validation: false
    fields:
        -
            name: name
            display_label: false
            classes: form-control
            placeholder: 'Your name *'
            autofocus: 'off'
            autocomplete: 'on'
            type: text
            position: left
            validate:
                required: true
        -
            name: email
            display_label: false
            classes: form-control
            placeholder: 'Your email address *'
            type: email
            position: left
            validate:
                required: true
        -
            name: message
            display_label: false
            placeholder: 'Your message *'
            type: textarea
            classes: form-control
            position: right
            validate:
                required: true
    buttons:
        -
            type: submit
            classes: 'btn btn-primary btn-lg'
            value: 'Send Message'
    process:
        -
            save:
                fileprefix: message-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
                operation: create
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: '{{ config.plugins.email.to }}'
                subject: 'SGC Website: Contact form message'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            message: 'Thank you for your message - we will respond to you as soon as possible.'
        -
            reset: true
```

This was working fine with Grav 1.6.3 and displayed the thank you message above the form when it returned to the page. However, since upgrading to Grav 1.6.8 the message no longer shows.

I discovered that if I take out the `reset: true` process item then the message does show again.
