### ISSUE TITLE
Date field error

### ISSUE THREAD

**Issue by BermudaStudio** [getgrav/grav-plugin-form#341]
I can't validate any form with "date" field. (missing field : Date)
French datepicker seems to not be compliant with the plugin. (dd / mm / yyyy)
Thanks.

**Comment by BermudaStudio** [comment]
Resolved :
Old code :
```
            type: date
            label: 'Date de l’événement'
            validate.min: '2019-01-01'
            validate.max: '2025-12-31'
            validate:
                required: true
```
New code OK :
```
            name: date
            label: 'Date de l’événement'
            autofocus: 'on'
            autocomplete: 'on'
            type: date
            validate.min: '2019-01-01'
            validate.max: '2025-12-31'
            validate:
                required: true
```
