### ISSUE TITLE
Checkbox value empty

### ISSUE THREAD

**Issue by jraack** [getgrav/grav-plugin-form#343]
Hi all,

I was updating grav to the latest version, and the form plugin as well.
Now checkboxes are not saved anymore. Previously it was saving the label, with yes/no value.

```

---
title: A Page with an Example Form
form:
    name: contact-form
    fields:
        - name: name
          label: Name
          placeholder: Enter your name
          autofocus: on
          autocomplete: on
          type: text
          validate:
            required: true

        - name: email
          label: Email
          placeholder: Enter your email address
          type: email
          validate:
            required: true
        - name: test
          label: I agree
          type: checkbox
    buttons:
        - type: submit
          value: Submit
        - type: reset
          value: Reset

    process:
        - save:
            fileprefix: feedback-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        - message: Thank you for your feedback!
        - display: thankyou

---

# My Form

Regular **markdown** content goes here...

```

When i submit, it saves only the field name, with an empty value.

Is my yaml correct?

Thanks in advance.

**Comment by rhukster** [comment]
Think this one requires this Grav fix: 

https://github.com/getgrav/grav/commit/0acb38f5867606409c860304c4711172c7de3a5d

**Comment by jraack** [comment]
@rhukster Thanks! that was exactly the problem.

**Comment by Jimmybow123** [comment]
> Think this one requires this Grav fix:
> 
> [getgrav/grav@0acb38f](https://github.com/getgrav/grav/commit/0acb38f5867606409c860304c4711172c7de3a5d)

Is I am currently having the same problem, where the value of a checkbox on my form isn't being saved, and only a null value is being returned. I checked and I have grav version 1.6.9, which has the code change specified above. Any thoughts?

**Comment by mahagr** [comment]
Do you have a small example on how to reproduce this issue of yours?

**Comment by drzraf** [comment]
The behavior is:

With **default: true**
```yaml
        ap:
            label: foo
            type: checkbox
            id: ap_field
            default: true
```


```html
        <label class="form-checkbox" for="ap_field-">
        <input name="ap" value="1" type="checkbox" id="ap_field-" checked="checked" class="">
            <div class="box"></div>
            <div class="label">foo</div>
        </label>
```

Sounds ok.

With **default: false**
```yaml
        ap:
            label: foo
            type: checkbox
            id: ap_field
            default: false
```

```html
        <label class="form-checkbox" for="ap_field-">
        <input name="ap" value="" type="checkbox" id="ap_field-" class="">
            <div class="box"></div>
            <div class="label">foo</div>
        </label>
```

In that case, if that checkbox is checked and form submitted, then the backend (Grav or something else) receives `ap=` (empty value). It would be preferable to receive `ap=1` or `ap=on`.

Basically:
- checkbox value is inconsistent (because it depends upon the checked default status)
- We miss control over its `value`.
