### ISSUE TITLE
upload file - nothing happens....

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav-plugin-form#349]
no error, save form work fine, but write to file (form save) - 'myfile: null' and image does not appear in destination....my code is
```
        myfile:
            type: file
            label: A Label
            destination: 'user/temp'
            multiple: true
            autofocus: false
            accept:
            - image/* 
```       
image simplte jpg 200kb.
dir present... no error displayed...
```
{% block bottom %}
    {{ assets.js('bottom')|raw }}
{% endblock %}
```
present

**Comment by abooks23** [comment]
help please

**Comment by rhukster** [comment]
I created a new test file:

```
---
title: Attachment Test

form:
    name: join-form
    fields:
      myfile:
        type: file
        label: A Label
        destination: 'user/temp'
        multiple: true
        autofocus: false
        accept:
          - image/* 
    buttons:
      - type: submit
        value: Submit
    process:
      reset: true
      message: Thanks!

---

File Upload Test: https://github.com/getgrav/grav-plugin-form/issues/349
```

Then I created a `user/temp` folder and **made sure my webserver could write to it**, Tried the form and it uploaded fine:

![Image 2019-05-27 at 12 07 06 PM](https://user-images.githubusercontent.com/1084697/58409140-18157100-8078-11e9-8395-9b00d4a99889.png)

The test file was uploaded correctly to `user/temp/` location.
