### ISSUE TITLE
Submit & Redirect not working as expected (3.0.5)

### ISSUE THREAD

**Issue by yatiac** [getgrav/grav-plugin-form#355]
The submit action is not working as expected when there is no explicit redirection, the base url was removed in v3.0.5 and this is causing an issue when just submiting but no redirecting. (it was working fine in v3.0.4)

**Comment by rhukster** [comment]
If you have a `reset: true` make sure it's **NOT** after the `redirect:` in the form actions.. it will clear the redirect out.

**Comment by yatiac** [comment]
this is my form:

```
title: Contacto
form:
    name: contact
    fields:
        name:
            label: Nombre
            placeholder: 'Introduzca su nombre'
            autocomplete: 'off'
            type: text
            validate:
                required: true
        email:
            label: Email
            placeholder: 'Introduzca su e-mail'
            type: email
            validate:
                required: true
        message:
            label: Mensaje
            placeholder: 'Introduzca su mensaje'
            type: textarea
            validate:
                required: true
    buttons:
        submit:
            type: submit
            value: Enviar
            classes: button
    process:
        email:
            subject: '[Contacto desde Web] {{ form.value.name|e }}'
            body: '{% include ''forms/data.html.twig'' %}'
        message: 'Gracias por su interés, estaremos contactándolo en breve'
```

and it was working in v3.0.4
