### ISSUE TITLE
HTML in Frontmatter or form label?

### ISSUE THREAD

**Issue by noelacosta** [getgrav/grav-plugin-form#370]
Not sure if this is the correct place to post this (or is this about grav-form) but I don't know how to make clickable links in form element text. Here's a sample:

```
        -
            name: press_info
            type: radio
            label: 'Would you prefer to receive press information links via email? [Sample link](http://ntrdr.com)'
            validate:
                required: true
            options:
                'yes': 'Yes'
                'no': 'No'
```
It only renders as plain text (as typed) in Frontmatter or the actual page. Thank you.

**Comment by noelacosta** [comment]
Going to answer my own question. Tried adding `markdown: true` in the radio element declaration. Hopefully this will help someone who looks here. And also hope for better documentation.

```
-
            name: press_info
            type: radio
            markdown:true
            label: 'Would you prefer to receive press information links via email? [Sample link](http://ntrdr.com)'
            validate:
                required: true
            options:
                'yes': 'Yes'
                'no': 'No'
```
