### ISSUE TITLE
Problem with textArea new lines

### ISSUE THREAD

**Issue by VincentFericelli** [getgrav/grav-plugin-form#371]
I try to build a very simple comment system with a form and a textArea and then store in a yaml file.

I try to remove the new line with replace but there is still a new line character, but I don't understand how.

Here is my form, if someone has an idea

```
---
title: Nouveau Commentaire
form:
    name: comment-form
    classes: 'formSubmitStayOnPage'
    fields:
        - name: name
          label: Pseudo
          autocomplete: on
          type: text
          validate:
            required: true

        - name: comment
          label: commentaire
          autocomplete: on
          type: textarea
          validate:
            required: true

        - name: date
          type: hidden
          process:
            fillWithCurrentDateTime: true

        - name: lang
          type: hidden
          evaluateDefault: grav.language.getLanguage

        - name: path
          type: hidden
          evaluateDefault: grav.uri.path

    buttons:
        - type: submit
          value: Commenter
          classes: 'actionButton'

    process:
        - save:
            filename: "{{form.value.lang}}/{{ grav.uri.path}}.yaml"
            body: "- { author: {{ form.value.name|e }}, date: '{{ form.value.date|date('m/d/Y')}}', text: '{{ form.value.comment|replace({ '\r\n': '<br/>' , '\n': '<br/>' , '\r': '<br/>' }) }}', lang: {{form.value.lang}} }\n"
          operation: add
        - reset: true
        - message: Commentaire enregistré !
---
```
