### ISSUE TITLE
Form is not rendered

### ISSUE THREAD

**Issue by holzleitner** [getgrav/grav-plugin-form#373]
Hi Grav team!

I have created a modular page and integrated a form with a file field, but only the form itself without the fields is rendered.

My form:
```yaml
cache_enable: false
forms:
    quick-contact-form:
        action: '/thank-you'
        inline_errors: true
        fields:
            name:
                type: text
                display_label: false
                placeholder: FORM.NAME
                validate:
                    required: true
            upload:
                type: file
                display_label: false
                destination: 'user/data/uploads'
                multiple: true
                limit: 10
                avoid_overwriting: true
                filesize: 10
                accept:
                    - image/*
            honeypot:
                type: honeypot

        buttons:
            submit:
                type: submit
                value: FORM.SEND

        process:
            - 
                email:
                    from: "{{ config.plugins.email.from }}"
                    to: "{{ config.plugins.email.to }}"
                    subject: "Quick contact"
                    body: "{% include 'forms/quick-contact.txt.twig' %}"
                    attachments:
                        - upload
            -
                reset: true
```

Generated HTML:
```html
<form name="" action="/de" method="POST" class=" ">
<input type="hidden" name="__form-name__" value="">
<div class="buttons">
</div>
<input type="hidden" name="__unique_form_id__" value="anDqolAydPB4x0XwNFYR">
<input type="hidden" name="form-nonce" value="847ad98cc3a6a6ffea514a06f9b0437b">
</form>
```

This is my system.yaml:
```yaml
absolute_urls: false
param_sep: ':'
wrapped_site: false
reverse_proxy_setup: false
force_ssl: false
force_lowercase_urls: true
custom_base_url: 'https://foobar.com'
username_regex: '^[a-z0-9_-]{3,16}$'
pwd_regex: '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}'
intl_enabled: true
languages:
  supported:
    - de
    - en
  include_default_lang: true
  pages_fallback_only: false
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: true
  override_locale: false
home:
  alias: /home
  hide_in_urls: false
pages:
  theme: foobar
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    short: 'jS M Y'
    long: 'F jS \a\t g:ia'
  publish_dates: true
  process:
    markdown: true
    twig: false
  twig_first: false
  never_cache_twig: false
  events:
    page: true
    twig: true
  markdown:
    extra: false
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
    special_chars:
      '>': gt
      '<': lt
  types:
    - html
    - htm
    - xml
    - txt
    - json
    - rss
    - atom
  expires: 604800
  cache_control: no-cache
  last_modified: true
  etag: true
  vary_accept_encoding: false
  redirect_default_route: false
  redirect_default_code: '302'
  redirect_trailing_slash: true
  ignore_files:
    - .DS_Store
  ignore_folders:
    - .git
    - .idea
  ignore_hidden: true
  url_taxonomy_filters: true
  frontmatter:
    process_twig: false
    ignore_fields:
      - form
      - forms
  markdown_extra: false
cache:
  enabled: true
  check:
    method: file
  driver: file
  prefix: foobar
  purge_at: '0 4 * * *'
  clear_at: '0 3 * * *'
  clear_job_type: standard
  clear_images_by_default: true
  cli_compatibility: false
  lifetime: 604800
  gzip: true
  allow_webserver_gzip: false
  redis:
    server: localhost
    port: '6379'
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false
  undefined_functions: true
  undefined_filters: true
  umask_fix: false
assets:
  css_pipeline: true
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_minify_windows: false
  css_rewrite: true
  js_pipeline: false
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: true
  js_minify: true
  enable_asset_timestamp: true
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
errors:
  display: 0
  log: true
log:
  handler: file
  syslog:
    facility: local6
debugger:
  enabled: false
  shutdown:
    close_connection: true
  twig: true
images:
  default_image_quality: 90
  cache_all: false
  cache_perms: '0755'
  debug: false
  auto_fix_orientation: false
  seofriendly: false
media:
  enable_media_timestamp: false
  auto_metadata_exif: false
  upload_limit: 8388608
session:
  enabled: true
  initialize: false
  timeout: 1800
  name: foobar
  uniqueness: path
  secure: false
  httponly: true
  split: true
gpm:
  releases: stable
  method: auto
  verify_peer: true
  official_gpm_only: true
accounts:
  type: data
  storage: file
strict_mode:
  yaml_compat: true
  twig_compat: true
```

Does anybody know why the fields are not created?
