### ISSUE TITLE
Grav modular page success message issues

### ISSUE THREAD

**Issue by alljamin** [getgrav/grav-plugin-form#375]
```yaml
---
...
form:
 name: contact-form
 action: /home
 ...
 process:
 - message: "Thank you!"
...
---
```

This shows a success message once submit button is clicked. The success message stays on the page even if the cache is reset shift+cmd+R.

Is there a way to control styling and state of the success message? For example, upon submission success message shows for 5 seconds and then disappears reseting the form to its original state.
