### ISSUE TITLE
Submit custom form markup without fields definitions in frontmatter.

### ISSUE THREAD

**Issue by Genenenenaam** [getgrav/grav-plugin-form#377]
I would like to handle html form markup myself and not use frontmatter for this.

Question: Would it be possible to only define a `name` and `process` in frontmatter to handle form submission with JS/Ajax?

Frontmatter would look like this:
```
---
title: A Page with an Example Form
form:
    name: contact-form
    process:
        - email:
            from: "{{ config.plugins.email.from }}"
            to:
              - "{{ config.plugins.email.to }}"
              - "{{ form.value.email }}"
            subject: "[Feedback] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
        - save:
            fileprefix: feedback-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        - message: Thank you for your feedback!
---
```
