### ISSUE TITLE
Unexpected name given to field

### ISSUE THREAD

**Issue by OleVik** [getgrav/grav-plugin-form#379]
When setting the [Common Field Attribute](https://learn.getgrav.org/16/forms/forms/fields-available#common-field-attributes) `name` as a property in a field, it is not reflected in the HTML:

```yaml
mysection:
  type: section
  title: Options
  underline: true
  fields:
    foobar:
      name: bear
      type: select
```

Renders as:

```html
<select name="data[foobar]" class="selectized" tabindex="-1" style="display: none;">
    <option value="" selected="selected"></option>
</select>
```

Whereas I would expect it to be `select name="data[bear]"`. Why is the dictionary's key preferred over the field's name-property?

**Comment by mahagr** [comment]
Actually the key always overrides the name, so the result you're getting is correct.

**Comment by OleVik** [comment]
Is this desirable? Even if I use a list of fields, like:

```yaml
mysection:
  type: section
  title: Options
  underline: true
  fields:
    - name: bear
       type: select
```

The key would be `0`, which isn't very helpful when trying to assign the data somewhere. The `name`-property contains information about where I want it assigned, whereas the key or index is just a necessary precondition for creating it altogether.

If I used the key `foobar` just as a placeholder, but wanted the assignment to depend on some logic from a static call, `name` can be set by this logic - allowing me to switch between for example `bear` some places and `header.something.bear` for a Page. To make the field-definitions reusable, `name` should take precedence.

**Comment by mahagr** [comment]
Your YAML has bad inlining, `type` is not the same level as `name`.

Please do not use a list of fields; always name them as in your first example (foobar).

There's a reason why the key overrides name and it's because of you cannot have dynamic names in blueprints; it will break the validation of the fields as well as assigning existing values.

**Comment by OleVik** [comment]
The YAML notwithstanding, the key is not necessarily static. If I use `data-fields@` I can call a method with parameters, to deliver an array simulating the fields, and assigning keys based on the parameters. A simplified example:

`/blueprints/partials/basic.yaml`:
```yaml
enabled:
  type: toggle
  label: PLUGIN_ADMIN.PLUGIN_STATUS
  options:
    1: PLUGIN_ADMIN.ENABLED
    0: PLUGIN_ADMIN.DISABLED
  validate:
    type: bool
```

And in my extension:
```php
/**
 * Get configuration blueprints
 *
 * @param string $path   Path to blueprint
 * @param string $prefix Optional key-prefix
 *
 * @return array Associative, nested array of settings
 */
public static function getConfigBlueprintFields(string $path, string $prefix = ''): array
{
    $config = Grav::instance()['config'];
    $locator = Grav::instance()['locator'];
    $formatter = new YamlFormatter;
    $file = new YamlFile($locator->findResource($path, true, true), $formatter);
    $return = array();
    foreach ($file->load() as $name => $data) {
        foreach ($data as $key => $property) {
            if (Utils::contains($key, '@')) {
                $key = str_replace(['data-', '@'], '', $key);
                if (is_string($property)) {
                    $data[$key] = call_user_func_array(
                        $property,
                        []
                    );
                } elseif (is_array($property)) {
                    $data[$key] = call_user_func_array(
                        $property[0],
                        array_slice($property, 1, count($property)-1, true)
                    );
                }
            }
        }
        if (!isset($data['name'])) {
            $data['name'] = $prefix . $name;
        }
        if (!isset($data['default']) && $config->get('theme.' . $name)) {
            $data['default'] = $config->get('theme.' . $name);
        }
        $return [$prefix . $name] = $data;
    }
    return $return;
}
```

And in `/blueprints.yaml` passing:
```yaml

form:
  validation: strict
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        options:
          type: tab
          title: PLUGIN_ADMIN.OPTIONS
          data-fields@:
            [
              '\Grav\Theme\Scholar::getConfigBlueprintFields',
              "user://themes/scholar/blueprints/partials/basic.yaml",
            ]
```

Whilst in `/blueprints/default.yaml`:
```yaml
form:
  fields:
    tabs:
      type: tabs
      fields:
        options:
          type: tab
          fields:
            scholar_basic:
              type: section
              title: THEME_SCHOLAR.ADMIN.TITLES.BASIC
              underline: true
              data-fields@:
                [
                  '\Grav\Theme\Scholar::getConfigBlueprintFields',
                  "theme://blueprints/partials/basic.yaml",
                  "header.theme.",
                ]
```

Thus yielding the same set of options from a file containing a normal list of fields in the context of Plugin-settings, and FrontMatter-settings, without duplicating the field-definitions.

I know this is a bit beyond how blueprints are normally used, but I find it pertinent to reduce duplication as much as possible, and to keep the definitions extendable.
