### ISSUE TITLE
Can't use Recaptcha v3 in form with AJAX

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-form#380]
Hello!

I used previously Captcha v2 with "I'm not a robot" check, worked fine. Some time ago I saw more spam in my inbox and decided to change Captcha to v3.

I have form in different non-modular page in `contacts.ru.md` and `contacts.en.md`:
![image](https://user-images.githubusercontent.com/7556290/68682396-1f70fe00-0576-11ea-9b1e-b3274ca8e2aa.png)

My form definition (Captcha field based on [learn](https://learn.getgrav.org/16/forms/forms/fields-available#captcha-field)):
```yaml
cache_enable: false
title: Contacts

form:
    name: contact-form
    classes: send-form
    template: form-messages
    #refresh disable
    refresh_prevention: true

    fields:

        name:
            label: Name
            placeholder:  Your name
            outerclasses: 'col-md-6'
            type: text
            validate:
                required: true

        mail:
            label: Email
            type: email
            placeholder: Your e-mail
            outerclasses: 'col-md-6'
            validate:
                required: true

        message:
            label: Message
            placeholder: Your message
            outerclasses: 'col-md-12'
            type: textarea
            validate:
                required: true

        g-recaptcha-response:
            display_label: false
            outerclasses: 'col-md-12'
            type: captcha
            recaptcha_not_validated: 'Captcha isn't pass!'
            validate:
                required: true

        honeypot:
            type: honeypot

    buttons:
        submit:
            type: submit
            value: Send

    process:
        captcha: true
        email:
            from: "{{ config.plugins.email.from }}"
            to:
                - "{{ config.plugins.email.to }}"
            subject: "Message from [mysite.ru/ru]"
            body: "{% include 'forms/data.html.twig' %}"
        message: 'Thank you!'
```

js AJAX part based on [learn example](https://learn.getgrav.org/16/forms/forms/how-to-ajax-submission):
```js
    var form = $('form.send-form');
    form.submit(function(e) {
        // prevent form submission
        e.preventDefault();

        // submit the form via Ajax
        $.ajax({
            url: form.attr('action'),
            type: form.attr('method'),
            dataType: 'html',
            data: form.serialize(),
            success: function(result, status, jqXHR) {

                 console.log(result);
                 console.log(status);
                 console.log(jqXHR);

                 new Noty({
                    theme: 'metroui',
                    layout: 'topCenter',
                    text: result,
                    timeout: 5000
                }).show();

            }
        });
    });
```
I develop on localhost and generated new v3 keys. Here my list of domains:
![image](https://user-images.githubusercontent.com/7556290/68680483-c6539b00-0572-11ea-9a38-f3cf68cb8f52.png)

Form options with v3 keys:
![image](https://user-images.githubusercontent.com/7556290/68681134-e9327f00-0573-11ea-8233-e943d8eb11f7.png)

Finally my form with Captcha badge:
![image](https://user-images.githubusercontent.com/7556290/68682897-edac6700-0576-11ea-8a9a-d89befe79d39.png)

Steps:
1. With `refresh_prevention: true` I see Captcha fail:
![image](https://user-images.githubusercontent.com/7556290/68683203-72978080-0577-11ea-86c4-6d876bdcc734.png)
After a second my page refreshed with white screen and "This form has already been submitted." message. No mail in inbox.
2. Without `refresh_prevention: true` I see the same Captcha fail, but success message "Thank you!" on white screen. Mail sended.
3. Without `refresh_prevention: true` and without `captcha: true` (`process` section) I see success message:
![image](https://user-images.githubusercontent.com/7556290/68688069-32d49700-057f-11ea-9469-890efdd74b88.png)
after that page refresh again with white screen and message "Thank you!". Mail sended.

Looks like Google for some reason refreshes the page:
![image](https://user-images.githubusercontent.com/7556290/68688644-33216200-0580-11ea-97c7-b2f2471a8b0e.png)

How to make it work?

Grav 1.6.17, Forms 4.0.0
