### ISSUE TITLE
array-value within a hidden field

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav-plugin-form#388]
A custom admin-field I developped is dynamically creating subfields on the fly.

For example:
```
    header.form.field_selection:
      type: my-custom-type
      fields:
        firstname:
          content: First name
```
would submit `data[header][form[firstname]` **and** `data[header][form][_is_required][firstName] = 0 or 1`

Since `_is_required` is not `known` to the blueprint, it ends-up in `blueprint.extra`, thus creating a hidden element under `[data][_json]` which, sadly, *always* take-over my submitted values
=> data is not saved.

In order to avoid that, I added a:
```
    header.form._is_required:
      type: hidden
```
to my form.

The problem is that with such a hidden field, the POST submission looks like:
```
data[header][form][_required] = ""
data[header][form][_required][firstname] = 1
```
=> data is not saved because the array structure is disregarded.

I ended-up finding the following **workaround** appending a single-quoted empty string:
```
    header.form._is_required.'':
      type: hidden
```

but I feel like it's a dirty (and not very future-proof) workaround.

**Comment by mahagr** [comment]
Those extra inputs must be outside of data. You still have access to them when handling the form.

**Comment by drzraf** [comment]
Yes, but since these extra are forcefully output as hidden fields, I can hardly provide myself an extra widget to override them, that result in:
```
<input type="TEXT" id="my-widget" name="data[_json][form][header][_required][foo]" value="1" />
<input data-grav-field="HIDDEN" data-grav-disabled="false" type="hidden" class="input" name="data[_json][form][header][_required][foo]" value="&quot;1&quot;">
```
Since the hidden fields are output **after** in the `<form>` it's probable (although webserver-dependant), that previous values are ignored.

(There is another bug in that the value is nested between extra-escaped-quotes: `&quot;`)

**Comment by drzraf** [comment]
Got it after digging system/src/Grav/Common/Data/Validation.php
```yaml
    header.form._is_required:
      type: checkbox
      validate:
        ignore: yes
```
