### ISSUE TITLE
Form not executed when caching turned on

### ISSUE THREAD

**Issue by rgenswaider** [getgrav/grav-plugin-form#39]
We use forms with the email plug-in for a contact form - as used in the theme skeleton for the theme "deliver". On our production environment we use caching - it's turned on in */user/config/system.yaml*.
```
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'
```
As soon as caching is turned on, the POST request from the form does not trigger the processing but only shows the contact form again. This happens because the contact form is cached. Setting cache_enable to false for the contact page also doesn't seem to work.
