### ISSUE TITLE
Contact form doesn't send the message and reload the page

### ISSUE THREAD

**Issue by Mehditeranee** [getgrav/grav-plugin-form#403]
Hi,

I try to implement a contact form on my one-page site. 

My folder structure for the form is : 
* user
     *pages
        *01.home
             *modular.md
             *_form
                 *form.md

The content of **_modular.md_** is :
`---
title: Mehdi GALLOIS
menu: Accueil
onpage_menu: true
body_class: index
header_class: alt
content:
    items: @self.modular
    order:
        by: default
        dir: asc
        custom:
            - _showcase
            - _callout
            - _pricing
            - _features
            - _diplomes
            - _screenshots
            - _form
            
       
---`

The content of **_form.md_** is : 

`---
title: Contact Form
routable: false
cache_enabled: false
form:
    action: /home
    name: contact
    refresh_prevention: true

    fields:
        name:
          label: Name
          placeholder: Enter your name
          autocomplete: on
          type: text
          validate:
            required: true

        email:
          label: Email
          placeholder: Enter your email address
          type: email
          validate:
            required: true

        message:
          label: Message
          placeholder: Enter your message
          type: textarea
          validate:
            required: true
            
    buttons:
        submit:
          type: submit
          value: Submit
        reset:
          type: reset
          value: Reset

    process:
        captcha: false
        save:
            fileprefix: contact-
            dateformat: Ymd-His-u
            extension: txt
            body: "{% include 'forms/data.txt.twig' %}"
        email:
            subject: "[Site Contact Form] {{ form.value.name|e }}"
            body: "{% include 'forms/data.html.twig' %}"
            from: "{{ config.plugins.email.from }}"
            from_name: "{{ config.plugins.email.from_name }}"
            to: "{{ config.plugins.email.to }}"
            to_name: "{{ config.plugins.email.to_name }}"
            content_type: 'text/plain'
            process_markdown: true
        reset: true
        message: 'Votre message a bien été envoyé.'

---

# Contact form

Some sample page content`

The actual behavior by clicking on the SUBMIT button is : 
- no message sent
and
- the one-page reload

The email plugin is correctly configured (with Google Email settings) and after tests of the plugin, mails are well sent. 

But impossible to send via the contact form. 

Someone could help me with this issue?

**Comment by hering** [comment]
Hi, do you have cookies enabled? 
When I submit the form without cookies enabled, the page reloads and the form is not sent.
It would be helpful if that requirement for cookies could be removed for anonymous sessions (considering the European Union's privacy policy).
HTH

**Comment by Mehditerranee** [comment]
> Hi, do you have cookies enabled? When I submit the form without cookies enabled, the page reloads and the form is not sent. It would be helpful if that requirement for cookies could be removed for anonymous sessions (considering the European Union's privacy policy). HTH

Hmm, I think there is just session cookie enabled. 

Since my post, I added the AJAX part to prevent reload:
```
<div id="form-result"></div>

<script>
$(document).ready(function(){

   var form = $('form[name="contact"]');

   var formData = new FormData();
   console.log(Object.values(form)[0]);
   form.submit(function(e) {
      // prevent form submission
      e.preventDefault();
      console.log(form);
      console.log(Object.values(form)[0]);
      console.log(form.serialize());
      // submit the form via Ajax
      $.ajax({
         url: form.attr('action'),
         type: form.attr('method'),
         dataType: 'html',
         data: form.serialize(),
         success: function(result) {
             // Inject the result in the HTML
             console.log(result);
          },
          // The following is added for debugging purposes.
          error: function(result) {
             // Inject the result in the HTML
             $('#form-result').html(result.responseText);
          }
      });
   });
});
</script>
```

And I also added a new folder for action parameter 
`action: '/forms/ajax-test' `

In `/forms/ajax-test` I created a new form without AJAX: 

```
---
title: Contact Form
menu: Contacts
cache_enable: false

form:
    refresh_prevention: true
    name: contact-test
    classes: 'g-grid cs_contact_cont-form'
    

    fields:
        name:
          label: Nom
          placeholder: Entrez votre prénom - nom
          autocomplete: 'on'
          type: text
          validate:
            required: true

        email:
          label: Email
          placeholder: Entrez votre adresse e-mail
          type: email
          validate:
            required: true

        objet:
          label: Objet
          placeholder: Entrez l'objet de votre message
          type: text
          validate:
            required: true

        message:
          label: Message
          placeholder: Ecrivez votre message
          type: textarea
          validate:
            required: true

        #g-recaptcha-response:
          #label: Captcha
          #type: captcha
          #recaptcha_not_validated: 'Captcha not valid!'
          #validate:
            #required: true

            
    buttons:
        submit:
          type: submit
          value: Envoyer

    process:
        #captcha: true
        ip:
          label: User IP Address

        email:
            from: '{{ config.plugins.email.from }}'
            to: '{{ config.plugins.email.to }}'
            subject: '[Formulaire de contact] {{ form.value.name|e }}'
            body: '{% include ''forms/data.html.twig'' %}'
            
        save:
            fileprefix: message-
            dateformat: Ymd-His-u
            extension: txt
            body: '{% include ''forms/data.txt.twig'' %}'

        reset: true
        message: 'Message envoyé. Je vous contacte au plus vite.'

        


---
# Contactez-moi
```

Now, the page doesn't reload but the email is not sent despite a 200 response code from `ajax-test`

despite
--




despite
--
