### ISSUE TITLE
Buttons should accept `name`

### ISSUE THREAD

**Issue by randoum** [getgrav/grav-plugin-form#411]
Hello,

I suggest that buttons accept `name` attribute, so a form can have multiple submit and on the server-side we can determine which was clicked.
Also the `value` attribute should be an attribute of the rendered button HTML tag.

```
  buttons:
    - type: submit
      name: trigger
      value: Compute
    - type: submit
      name: trigger
      value: Back
```

would output :

```
<div class="buttons">
  <button type="submit" name="trigger" value="Compute">Compute</button>
  <button type="submit" name="trigger" value="Back">Back</button>
</div>
```

How does that sound ?
