### ISSUE TITLE
Print Twig in form field

### ISSUE THREAD

**Issue by bluis4** [getgrav/grav-plugin-form#420]
Hi,

is it possible to print twig variable (something like page.header.title) inside a form field ? 

for example : 

```
---
title: A Page with an Example Form
form:
    name: contact-form
    fields:
        - name: name
          label: Name
          placeholder:  {{ page.header.title }}
          autofocus: on
          autocomplete: on
          type: text
          validate:
            required: true

    buttons:
        - type: submit
          value: Submit
        - type: reset
          value: Reset
---
```
