### ISSUE TITLE
File won't upload when form is on homepage

### ISSUE THREAD

**Issue by Saphareas** [getgrav/grav-plugin-form#425]
I've encountered this while testing why my files uploaded via a form would be saved sometimes, but wouldn't other times. My homepage is modular and my form is a module of this site. When I'm at ```example.com/``` and try to upload a file, the file won't be saved on the server and also won't be attached to e-mails. But when I'm at ```example.com/home``` everything is working as expected. The issue persists if the form is not part of a modular site.

Simple page I used for testing:
```
---
title: 'Test Form'
html_id: participate
process:
    twig: true
cache_enable: false
form:
    name: test_form
    fields:
        -
            name: datei
            label: Photo
            type: file
            multiple: false
            destination: user/data/uploads
            random_name: false
            filesize: 100000
            accept:
                - 'image/*'
            autofocus: false
    buttons:
        submit:
            value: Submit
    process:
        email:
            from: '{{ config.plugins.email.from }}'
            to: '{{ config.plugins.email.to }}'
            subject: 'Teilnahme von {{ form.value.name|e }}'
            attachments:
                - datei
        reset: true
---
## {{ page.title }}
```

My theme's form template (Antimatter):
```
{% extends 'partials/base.html.twig' %}

{% block content %}

    {{ content }}
    {% include "forms/form.html.twig" %}

{% endblock %}
```

EDIT: I just realized that there's no 'save' action in the form's 'process' in my example. That's only due to me experimenting with different combinations of actions during debugging.
