### ISSUE TITLE
Field with option toggleable can not be set to disabled again

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav-plugin-form#430]
I have added the `toggleable` option to a pages select field in a plugin blueprints file.
When the config file does not yet contain the `custom_dialog_forms_page` variable the form shows the checkbox and the pages select field all disabled.

When I check the checkbox the field becomes enabled and I'm able to select a page. The selected page does correctly get saved as the value of the `custom_dialog_forms_page` variable in the config file.

Another click on the now enabled checkbox does disable the field. However, once the form gets saved and the page reloads the checkbox in checked and the field shows as enabled. Also the entry in the config file does not get removed when the toggleable checkbox state in unchecked.

```
custom_dialog_forms_page:
  type: pages
  toggleable: true
  size: medium
  classes: fancy
  label: Select page
  show_all: false
  show_modular: false
  show_root: false
  default: ''
```

I was hoping that by using the toggleable option I could come to the situation where no page is selected at all. The pages select field does not provide a "blank" or "none" value to select.

Am I using the option in the wrong way perhaps?
