### ISSUE TITLE
Dropzone file field changes text to "Undefined" when multiple forms present

### ISSUE THREAD

**Issue by hdwebpros** [getgrav/grav-plugin-form#434]
We've stumbled on an issue with the dropzone text. Dropzone file field changes the text to "Undefined" when multiple forms present. 

Grav: v1.6.26, tested on v1.7.0-rc.15 as well
Form: v4.1.0

Steps to reproduce:

- Default Grav, quark up
- Create a page with the form markdown in it (code below)
- In a page template, call both forms as described on https://learn.getgrav.org/16/forms/forms *(code below)
- Contact form will show undefined in the dropzone

Markdown to include on page:
```
forms:
    contact-form:
        fields:
            -
                name: name
                label: Name
                type: text
                classes: form-control
                validate:
                    required: true
            -
                name: email
                label: Email
                type: email
                classes: form-control
                validate:
                    required: true
            -
                name: tell-us-more
                label: 'Tell us some more'
                type: textarea
                classes: form-control
                validate:
                    required: true
            -
                name: my-file
                label: 'Add a file'
                type: file
                multiple: false
                destination: user/data/files
                accept:
                    - application/pdf
                    - application/x-pdf
                    - .doc
                    - .docx
                    - .stp
                    - .igs
                    - .dwg
                    - .dwx
                    - 'image/*'
                filesize: 5000
            -
                name: g-recaptcha-response
                display_label: false
                type: captcha
                recaptcha_not_validated: 'Captcha not valid!'
                validate:
                    required: true
        buttons:
            -
                type: submit
                value: 'Send us a note'
                classes: 'btn btn-primary'
        process:
            -
                captcha:
                    dummy: dummy
            -
                hdwpwebhook: true
            -
                email:
                    from: '{{ config.plugins.email.from }}'
                    to:
                        - email@email.com
                    subject: 'Contact Form Fillout'
                    body: '{% include ''forms/data.html.twig'' %}'
                    attachments:
                        - my-file
            -
                save:
                    fileprefix: null
                    dateformat: Ymd-His-u
                    extension: txt
                    body: '{% include ''forms/data.txt.twig'' %}'
            -
                redirect: /thank-you-contacting-us
    newsletter-form:
        fields:
            -
                name: email
                label: Email
                type: text
                classes: form-control
                validate:
                    required: true
            -
                name: g-recaptcha-response
                label: ' '
                type: captcha
                recaptcha_not_validated: 'Captcha not valid!'
                validate:
                    required: true
        buttons:
            -
                type: submit
                value: 'Click here to sign up!'
                classes: 'btn btn-primary'
        process:
            -
                captcha:
                    dummy: dummy
            -
                email:
                    from: '{{ config.plugins.email.from }}'
                    to:
                        - email@email.com
                    subject: 'Newsletter Form Fillout'
                    body: '{% include ''forms/data.html.twig'' %}'
            -
                save:
                    fileprefix: null
                    dateformat: Ymd-His-u
                    extension: txt
                    body: '{% include ''forms/data.txt.twig'' %}'
            -
                redirect: /thank-you-newsletter
```

Template form inclusion code:
```
{% include "forms/form.html.twig" with {form: forms('contact-form')} %}
{% include "forms/form.html.twig" with {form: forms('newsletter-form')} %}
```
