### ISSUE TITLE
No data saved after submit

### ISSUE THREAD

**Issue by skygate2012** [getgrav/grav-plugin-form#435]
Hi everyone, just installed Grav and everything is amazing. I stumbled upon a problem when setting up forms, I couldn't see any txt file under `user/data` folder after submitting the form. I just copied the form frontmatter from the examples. And there's no message after submitting, the form just resets. What went wrong?

```
title: 'A Page with an Example Form'
form:
    name: contact-form
    fields:
        -
            name: name
            label: Name
            placeholder: 'Enter your name'
            autofocus: 'on'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: email
            label: Email
            placeholder: 'Enter your email address'
            type: email
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Submit
        -
            type: reset
            value: Reset
    process:
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Thank you for your feedback!'
        -
            display: thankyou
```
