### ISSUE TITLE
Custom site.yaml blueprint doesn't support more than one fieldset

### ISSUE THREAD

**Issue by thekenshow** [getgrav/grav-plugin-form#443]
I have a `user/blueprints/config/site.yaml` file with a single fieldset that was working as expected. With the snippet below, the **Location Services** fieldset is rendered with the correct fields:

```
                accessconfirm:
                    type: markdown
                    label: 'Accessibility form confirmation message'                      
                rfpconfirm:
                    type: markdown
                    label: 'RFP form confirmation message'                      

                fieldset:
                  type: fieldset
                  title: 'Location Services'
                  text: 'The text and images below are used across Location pages where provided.'
                  collapsed: true
                  collapsible: true
                  fields:
                    photos:
                      label: 'Service Images'
                      type: file
                      destination: 'user/images/location/services'
                      multiple: true
                      accept:
                        - image/*
```

When I added another fieldset before this one, the new one appeared but the existing **Location Services** fieldset was no longer rendered. With the snippet below, the **Form Configuration** fieldset appears but the **Location Services** fieldset does not:

```
                whyworkwithus:
                    type: textarea
                    label: 'Why Work with Us?'                      
                fieldset:
                  type: fieldset
                  title: 'Form Configuration'
                  text: 'Customizing the Contact and other forms.'
                  collapsed: true
                  collapsible: true
                  fields:
                    contactconfirm:
                        type: markdown
                        label: 'Contact form confirmation message'                      
                    applyconfirm:
                        type: markdown
                        label: 'Application form confirmation message'                      
                    accessconfirm:
                        type: markdown
                        label: 'Accessibility form confirmation message'                      
                    rfpconfirm:
                        type: markdown
                        label: 'RFP form confirmation message'                      

                fieldset:
                  type: fieldset
                  title: 'Location Services'
                  text: 'The text and images below are used across Location pages where provided.'
                  collapsed: true
                  collapsible: true
                  fields:
                    photos:
                      label: 'Service Images'
                      type: file
                      destination: 'user/images/location/services'
                      multiple: true
                      accept:
                        - image/*
```
