### ISSUE TITLE
Save to JSON

### ISSUE THREAD

**Issue by abooks23** [getgrav/grav-plugin-form#446]
Saves the form data to a file (option)
used by

   ```
 process:
        -
            save:
                filename: ........
                operation: add
```

is it possible to save data in valid JSON file?
