### ISSUE TITLE
Request: Add attributes to form fields

### ISSUE THREAD

**Issue by ptarmic** [getgrav/grav-plugin-form#448]
I'm trying to create a contact form using alpine.js, however I need to add attributes to all the `form` and `button` elements on the form not just the fields. I have added the `attribute` field to my form.md file but they aren't used, I think because the attributes are set at the field level rather than the form level. For now I have overridden the  form and button twig files but now my fields are hardcoded into those files rather than coming through naturally from form.md.

My sample button code:

```
             type: submit
                value: callmeback.submit
                classes: 'bg-gray-700 hover:bg-gray-800 disabled:opacity-50 text-white w-full p-2 mb-4'
                attributes:
                  x-text: '"buttonLabel" :disabled="loading"'

```
