### ISSUE TITLE
RuntimeError when using checkbox, spacer or honeypot fields under PHP 7.4

### ISSUE THREAD

**Issue by AnneSalem** [getgrav/grav-plugin-form#457]
I get the following RuntimeError when using checkbox, spacer or honeypot fields under PHP 7.4. Under PHP 7.3 everything works as expected without errors.

```
An exception has been thrown during the rendering of a template 
("Trying to access array offset on value of type int").

.../user/plugins/form/templates/forms/default/field.html.twig9
```

The definition of the affected fields is done on a modular page and looks as follows:  

```
- agree_to_terms:
  type: checkbox
  validate:
    required: true
  outerclasses: privacy-checkbox

- agree_to_terms_text:
  type: spacer
  text: Ich habe die Datenschutzerklärung gelesen und bin einverstanden *

- honeypot:
  type: honeypot
```

**Issue exist on:**
- Grav v1.6.28
- Form v4.1.2
- PHP 7.4

Any ideas on how to solve this issue?

**Comment by rhukster** [comment]
Are you on the latest released version of Form plugin?  I can run fine under PHP 7.4, even PHP 7.8 with checkbox and radio fields.  I'll have to get a test page with your blueprint elements though (although they look fine).

**Comment by AnneSalem** [comment]
Thank you for the quick reply. 
Yes, the version is v4.1.2. I also tried to delete the plugin and reinstall it. In my case just one of the fields is enough to produce the error. Text inputs and textareas are working fine. 
Should I copy the whole form definition here?

**Comment by mahagr** [comment]
Try writing the form in this format:

```yaml
agree_to_terms:
  type: checkbox
  validate:
    required: true
  outerclasses: privacy-checkbox

agree_to_terms_text:
  type: spacer
  text: Ich habe die Datenschutzerklärung gelesen und bin einverstanden *

honeypot:
  type: honeypot
```

So basically remove dash from the form fields, it's not supported. 

PS: Dash format works without the key like this:

```yaml
-
  name: agree_to_terms
  type: checkbox
  validate:
    required: true
  outerclasses: privacy-checkbox
-
  name: agree_to_terms_text
  type: spacer
  text: Ich habe die Datenschutzerklärung gelesen und bin einverstanden *
-
  name: honeypot
  type: honeypot
```
