### ISSUE TITLE
Form is process by other page

### ISSUE THREAD

**Issue by acmngmbh** [getgrav/grav-plugin-form#491]
I have multiple pages with Forms (AJAX submitted). They contain different email-actions in the process section. 
When submitting them, the wrong process section is executed. What could be the reason for this?

```
form:
    name: contact
    client_side_validation: true
    action: /routetonowhere
    template: form-messages
    refresh_prevention: true
    reset: true
```

I am submitting as follows:

```
<script>
$(document).ready(function(){
    var form = $('#contact');
    form.submit(function(e) {
        // prevent form submission
        e.preventDefault();
        // submit the form via Ajax
        $.ajax({
            url: $(location).attr('href'),
            type: form.attr('method'),
            dataType: 'html',
            data: form.serialize(),
            success: function(result) {
                // Inject the result in the HTML
                $('#form-result').html('<b>Vielen Dank für Ihre Nachricht! Wir setzen uns schnellstmöglich mit Ihnen in Verbindung.</b>');
              $('#contact').hide();
            }
        });
    });
});
</script>
```
