### ISSUE TITLE
file upload (dropzone) with validate: required can not be submitted

### ISSUE THREAD

**Issue by stephan-strate** [getgrav/grav-plugin-form#499]
Creating a file upload (frontend form) with `required: true` leads to form being not submittable (with file selected and without). Error in console: `An invalid form control with name='' is not focusable.`. Tried to investigate it myself, but did not find any documentation on making dropzone fields required. In [Grav documentation](https://learn.getgrav.org/17/forms/forms/fields-available#file-field) it is listed as a valid common attribute. It also marks the field as required using `*`.

Example code:
```yaml
form:
  name: testform
  buttons:
    submit:
      value: Send
      type: submit
  fields:
    -
      label: File
      name: myfile
      type: file
      destination: user/data/form
      accept:
        - '*'
      multiple: false
      filesize: 10
      avoid_overwriting: true
      random_name: false
      validate:
        required: true
  process:
    save:
      body: '{% include ''forms/data.txt.twig'' %}'
      operations: add
      filename: form.txt
```

Versions:
Grav: v1.7.6
Form: v5.0.0
(did not work in version before as well)
