### ISSUE TITLE
Form fields in email are looking strange

### ISSUE THREAD

**Issue by beamaria** [getgrav/grav-plugin-form#503]
Hi all!
Before updating "form" plugin to ver.5 I had this email form fields:

**Name**: John Doe
**Email**: johndoe@info.td
**Message**: This is a test message
What is five times eight?: honeypot-correct-choice
<a href='#/privacy/privacy-policy' target='blank'>Please accept our privacy policy</a>: Yes

After updating I have this:

This is a test message

John Doe
johndoe@info.td

basically the email submitted now isn't so clear as before, when all the relevant fields were clearly written in bold and followed by the related values,; moreover the validation of honeypot and of Privacy policy fileds is missing.

Is there way to revert to the previous version display?

**Comment by beamaria** [comment]
SOLVED  I used this code in frontmatter

```
email:
                from:
                    mail: '{{ config.plugins.email.from }}'
                to:
                    mail: '{{ form.value.email }}'
                    name: '{{ form.value.name|e }}'
                reply_to: '{{ form.value.email }}'
                subject: '[Contact] New message from {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
```
