### ISSUE TITLE
File upload (dropzone): Unable to remove file if over limit

### ISSUE THREAD

**Issue by apxwn** [getgrav/grav-plugin-form#508]
If the form sets a limit on number of files (e.g. `multiple: false`) and you drop more than one file, you cannot remove this file, because the error message blocks the remove button.

Removing the first file still lets the error message pop up over the (then only) file that was superfluous in the first place.

```
Example:
form:
    name: Kontaktformular
(...)
        Dateianhang:
            type: file
            multiple: false
            destination: '@self'
            autofocus: false
            filesize: 5
            validate:
                required: false
            accept:
                - 'image/*'
                - application/pdf
```
results in:
![image](https://user-images.githubusercontent.com/15420626/110366137-2d3d7300-8046-11eb-8f4f-4a6e0ee0e8e8.png)

The error message blocks the x to remove the file.
There are actually a few pixels left and right of the bubble tail, but it's ofttimes a real challenge to find & click them.

Removing the first file keeps the error message popping up over the, then only, file left:

![image](https://user-images.githubusercontent.com/15420626/110366562-bf457b80-8046-11eb-9f60-242becd95b74.png)
