### ISSUE TITLE
Order of form fields when extending blueprint

### ISSUE THREAD

**Issue by marcelgwerder** [getgrav/grav-plugin-form#52]
Not quite sure if this belongs here but was the best match for me.

If I extend a blueprint to modify the content tab in the admin panel it looks like I don't really have control over the order of the fields. I want to add two fields below the title field, which I tried like this:

```yaml
title: Employee
@extends:
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          type: tab
          title: Employee
          fields:
            content:
              type: ignore

            header.function:
              type: text
              label: Function

            header.picture:
              type: pagemediaselect
              label: Picture

            uploads:
              type: pagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA
```

Even if I add the `uploads` field again below the two existing fields the order still seems to come from the inherited blueprint. The result is:

![image](https://cloud.githubusercontent.com/assets/4008557/13554847/c0e91a36-e3b2-11e5-96f5-9cd546c836d4.png)

The most flexible solution for me would be if I could somehow just override everything that comes below a specific attribute respectively stop inheritance there.

Maybe this is already possible or there is another way to solve my issue but I couldn't find anything in the docs.
