### ISSUE TITLE
Reset button don't work after clicking submit

### ISSUE THREAD

**Issue by Candidesk8** [getgrav/grav-plugin-form#520]
Hi there !

new to grav, I've been playing around to set a pro-page ...

had an issue [shared on the discourse](https://discourse.getgrav.org/t/agency-reset-button-on-contact-form/17421) and was told to submit this :

Grav v1.7.16
inherited theme from Agency
button in `grav/user/pages/01.home/_contact/form.md'

```
    buttons:
        - type: submit
          classes: "btn btn-primary btn-lg"
          value: Envoyer
        - type: reset
          classes: "btn btn-primary btn-lg"
          value: Effacer

```

reset work properly unless the submit button had been pressed.
then it don't do anything, and it's color don't change when the pointer is over it.
