### ISSUE TITLE
Using security@ with tabs breaks navigation

### ISSUE THREAD

**Issue by robertbak** [getgrav/grav-plugin-form#524]
If a tab is hidden, the tabs following it in the bar don't work correctly.

How to reproduce:
1) Create a page blueprint (eg. user/blueprints/pages/default.yaml) with:
```yaml
"@extends":
  type: default
  context: blueprints://pages
form:
  fields:
    tabs:
      type: tabs
      active: 1
      fields:
        advanced:
          security@: admin.foobar
```
2) In the admin panel open a page using that blueprint, try clicking "Security". It won't switch to that.
