### ISSUE TITLE
[form-captcha] captcha not working in contact form

### ISSUE THREAD

**Issue by rfvallina** [getgrav/grav-plugin-form#538]
Hello,
I enabled captcha verification in form plugin. I tried v2 and v3, but none is working.

- form plugin settings
```

recaptcha:
  version: '3'
  theme: light
  site_key: 6Le1tT4d...
  secret_key: 6Le1tT4d...
```

- page settings

```
process:
        captcha: true
```

When I click submit it shows error message
_reCAPTCHA bot protection has identified this form submission is problematic_

![image](https://user-images.githubusercontent.com/7671709/142256735-6d458649-2105-4958-9e7f-d7af8aed2523.png)

**Comment by rfvallina** [comment]
Thanks,
I fixed the issue.
The problem was that the captcha field was missing in the contact page. 
I had no idea that this was required.

```
g-recaptcha-response:  
            label: Captcha
            type: captcha
            recaptcha_site_key: 6Lez8D4d.........YDxv6dPCb2
            recaptcha_not_validated: 'Captcha not valid!'
            validate:
                required: true
```
