### ISSUE TITLE
recaptcha not showing

### ISSUE THREAD

**Issue by JohnMica** [getgrav/grav-plugin-form#54]
Hi guys, I have small issue with recaptcha as per the image attached, the api.js is loaded however the site key seems to be missing. I have just copied the form from learn.grav and for some reason all i get is the label captcha. any ideas why or how to solve this? the page is just a form.md page (not modular).
![captura de ecran din 2016 03 18 la 17 00 15](https://cloud.githubusercontent.com/assets/7076631/13885643/4d37bcfa-ed2b-11e5-9306-8f1dee40f2fe.png)

**Comment by flaviocopes** [comment]
Post your form.md file, without it it's hard to tell what could be wrong.

**Comment by JohnMica** [comment]
```
---
title: Contact
body_classes: 'header-image fullwidth'
form:
    name: Formular-Contact
    fields:
        -
            name: name
            label: Name
            placeholder: 'Enter your name'
            autofocus: 'on'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: email
            label: Email
            placeholder: 'Enter your email address'
            type: text
            validate:
                rule: email
                required: true
        -
            name: message
            label: Message
            size: long
            placeholder: 'Enter your message'
            type: textarea
            validate:
                required: true

        -
            name: g-recaptcha-response
            label: Captcha
            type: captcha
            recaptcha_site_key: 6LeXdxQTAAAAADeQJxfhjVYHUeorEHyP8S7cnnS-
            recaptcha_not_validated: 'Captcha not valid!'
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Trimite
        -
            type: reset
            value: Anuleaza
    process:
        - captcha:
            recaptcha_secret: 6LeXdxQTAAAAAJooMcpV33FhF0QH6KfsGmcFTYOu

        -
            email:
                from: '{{ config.plugins.email.from }}'
                to: ['{{ config.plugins.email.from }}', '{{ form.value.email }}']
                subject: '[Feedback] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Multumim pentru mesaj'
        -
            display: multumim
---

### Contactati-ne

```
