### ISSUE TITLE
select option group options don’t take keys

### ISSUE THREAD

**Issue by dani-ooo** [getgrav/grav-plugin-form#541]
select options don’t work when entering `key: value` formatting, either as `select` or `select_optgroup` fields. i’ve attempted multiple ways, but it doesn’t work.

the following renders the select field without any options:
```yaml
form.field:
  type: select
  options:
    - select_group:
      option_value: "option key"
```

and this other option throws an error:
```yaml
form.field:
  type: select
  options:
    - select_group:
      - option_value: "option key"
```
_An exception has been thrown during the rendering of a template ("Array to string conversion")._

i also tried doing it in the `selectize` structure, getting the same error:
```yaml
form.field:
  type: select
  options:
    - select_group:
      - text: "option key"
        value: option_value
```

**Comment by w00fz** [comment]
Duplicate of getgrav/grav-plugin-admin#2204

**Comment by w00fz** [comment]
This is now addressed. Thanks!

**Comment by hughbris** [comment]
@w00fz I am seeing getting an empty field control rendered on this test field:

```yaml
                options:
                  - OptGroup1:
                    Option1: 'Value!'
                    Option2: 'hey'
                  - OptGroup2:
                    Option3: 'moo'
                    Option4: 'cow'
```
Using Form 5.1.6.

I can sort of see where the wrong strings are being picked up in the template, but not how to adjust my YAML (which perhaps I shouldn't). Cheers.
