### ISSUE TITLE
Select Field not saving in plugin options in admin

### ISSUE THREAD

**Issue by jgonyea** [getgrav/grav-plugin-form#553]
tl;dr: Select form field saving is broken if `multiple` is set

I'm attempting to add a multiple select to my plugin configuration blueprints.yaml file.  In my file, I add the following:
```
    page_types:
      type: select
      size: long
      classes: fancy
      label: 'Page Types'
      help: 'Page types to be considered as assignable to group content.  Has CRUD implications for selected content.'
      options:
        default: 'Default - based on folder name'
        folder: 'Folder - based on prefix-less folder name'
        title: 'Title - based on title field in header'
        date: 'Date - based on date field in header'
      multiple: true
      validate.type: array
```
as a sibling of `enabled`.  Viewing the admin configuration of the plugin displays the select field as expected, and I can select multiple options. After pressing save, the field "page_types" is saved in the `user/config/plugins/PLUGINNAME.yaml` as `page_types: ''` (e.g. with no data).
