### ISSUE TITLE
No markdown support for a checkbox? But only for checkboxes?

### ISSUE THREAD

**Issue by kees-closed** [getgrav/grav-plugin-form#568]
In the [documentation for the checkbox](https://learn.getgrav.org/17/forms/forms/fields-available#checkbox-field) it is not mentioned if markdown supported is.

So therefore, I just tried:
```
        privacy-policy:
            label: 'Heb je onze [privacy verklaring](/privacy-verklaring) gelezen en ga je akkoord?'
            type: checkbox
            markdown: true
            validate:
                required: true
```

The checkbox part works great. However, no markdown support.

This is working with checkboxes:
```
        privacy-policy:
            label: 'Heb je onze [privacy verklaring](/privacy-verklaring) gelezen en ga je akkoord?'
            type: checkboxes
            markdown: true
            options:
                agreed: 'Gelezen en akkoord'
            validate:
                required: true
                message: 'Privacy verklaring'
```

Is there a way to enable markdown support for a checkbox in the same way (or another way) for the checkboxes?
