### ISSUE TITLE
Frontend File field tooltip blocks remove button when file is too large

### ISSUE THREAD

**Issue by james0r** [getgrav/grav-plugin-form#574]
A video is probably worth a 1000 words here.

https://user-images.githubusercontent.com/34731936/183279772-cb628f00-0780-45a0-9e61-b17b741ab691.mp4

**Comment by james0r** [comment]
Obviously subjective, but this worked for me to at least unobstructed the remove button:

```css
  .dropzone .dz-preview .dz-error-message {
      top: 150px !important;
    }

    .dropzone .dz-preview .dz-success-mark, .dropzone .dz-preview .dz-error-mark {
      top: calc(50% - 10px) !important;
    }
```
