### ISSUE TITLE
Default values for date type fields inside elements: only 1st default value is set.

### ISSUE THREAD

**Issue by MiguelVis** [getgrav/grav-plugin-form#576]
Hi all,

I have an issue regarding default values for date fields inside an elements field type.

The second date field (`date_end`) does not get the default value, only the first one (`date_start`).

JS is not complaining on console.

Any help please?

```
form:
  validation: loose

  fields:
   ...
    scheduling.type:
      type: elements
      label: EVENTS_PLUGIN.FREQUENCY_LABEL
      validate:
        required: true
      size: small
      default: one-time
      options:
        one-time: EVENTS_PLUGIN.ONE_TIME_SELECT_OPTION
        daily: EVENTS_PLUGIN.DAILY_SELECT_OPTION
        ...
      fields:
        one-time:
          ...
        daily:
          type: element
          fields:
            .date_start:
              type: date
              label: EVENTS_PLUGIN.START_DATE_LABEL
              default: "2099-01-01"
              validate:
                required: true
            .date_start_enabled:
              type: hidden
              value: true
            .date_end:
              type: date
              label: EVENTS_PLUGIN.END_DATE_LABEL
              default: "2099-01-01"
              validate:
                required: true
             ...
```
