### ISSUE TITLE
basic-captcha not showing image (404)

### ISSUE THREAD

**Issue by prismplex** [getgrav/grav-plugin-form#577]
### Description of the issue:
Captcha image is not displayed using basic-captcha in a modular page.
![human](https://user-images.githubusercontent.com/39129550/191621398-5c388dcf-c2b7-4df4-912a-b22d7be68fb8.png)

### Investigation:
Console throws: `Failed to load resource: the server responded with a status of 404 ()` trying to reach captcha image via `https://url.com/forms-basic-captcha-image.jpg?v=1663798282900`

### Current setup:
Modular page, reachable via `https://url.com/de/contact`

**Working configuration before embedding basic captcha:**
```
title: 'Contact form'
form:
    action: /contact
    name: contact-form
    fields:
        -
            name: name
            label: Name
            placeholder: 'Your name'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: firstname
            label: 'First Name'
            placeholder: 'Ihr Vorname'
            type: honeypot
        -
            name: email
            label: Email
            placeholder: 'Your email adress'
            type: email
            validate:
                required: true
        -
            name: message
            label: Message
            placeholder: 'Your message'
            type: textarea
            validate:
                required: true
        -
            name: terms
            label: 'I have read, understood and accepted the privacy policy.'
            type: checkbox
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Submit
        -
            type: reset
            value: Reset
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to:
                    - '{{ config.plugins.email.from }}'
                    - '{{ form.value.email }}'
                subject: '[Contact] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Danke für Ihre Nachricht!'
        -
            display: thankyou
```

**New configuration:**
```
title: 'Contact form'
form:
    action: /contact
    name: contact-form
    fields:
        -
            name: name
            label: Name
            placeholder: 'Your name'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: firstname
            label: 'First Name'
            placeholder: 'Ihr Vorname'
            type: honeypot
        -
            name: email
            label: Email
            placeholder: 'Your email adress'
            type: email
            validate:
                required: true
        -
            name: message
            label: Message
            placeholder: 'Your message'
            type: textarea
            validate:
                required: true
        -
            name: terms
            label: 'I have read, understood and accepted the privacy policy.'
            type: checkbox
            validate:
                required: true
        -
            name: basic-captcha
            type: basic-captcha
            placeholder: 'Bitte kopieren Sie die 10 Zahlen oder Buchstaben'
            label: 'Are you human?'
    buttons:
        -
            type: submit
            value: Submit
        -
            type: reset
            value: Reset
    process:
        -
            basic-captcha:
                message: 'Humanity verification failed, please try again...'
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to:
                    - '{{ config.plugins.email.from }}'
                    - '{{ form.value.email }}'
                subject: '[Contact] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Danke für Ihre Nachricht!'
        -
            display: thankyou
```

Am I missing something?
