### ISSUE TITLE
basic captcha: no letters are displayed

### ISSUE THREAD

**Issue by beamaria** [getgrav/grav-plugin-form#582]
Hi all. I'm trying to implement basic captcha in my form. This is my form:

```
title: 'Contact Form'
form:
    fields:
        name:
            type: text
            label: Name
            validate:
                required: true
                message: 'Please enter your name!'
        email:
            type: text
            label: Email
            validate:
                type: email
                required: true
                message: 'Please enter your email address!'
        subject:
            type: text
            label: Subject
            validate:
                required: true
                message: 'Please enter a subject for your message!'
        message:
            type: textarea
            label: Message
            validate:
                required: true
                min: 10
                message: 'Email message needs to be more than 10 characters long!'
        basic-captcha:
            type: basic-captcha
            label: 'Are you human?'
            placeholder: 'copy the 6 characters'
            validate:
                required: true
    buttons:
        submit:
            type: submit
            value: 'Send Email'
    process:
        basic-captcha:
            message: 'Humanity verification failed, please try again...'
        email:
            from: '{{ form.value.email }}'
            to: '{{ config.plugins.email.to }}'
            subject: '[Contact] {{ form.value.subject|raw }}'
            body: '{{ form.value.message }}<br /><br />{{ form.value.name }}<br />{{ form.value.email }}'
        message: 'Thank you from contacting us!'
        display: /form/thankyou
```

But when I go to my contact form no letters are displayed: 
<img width="1606" alt="Schermata 2022-11-18 alle 16 00 39" src="https://user-images.githubusercontent.com/11693902/202748743-47e98932-06ab-445e-ada9-7d561ef8dcd4.png">

I copied the documentation for basic captcha and I also tried to change the default values, but no success.
Working with:
Grav: 1.7.37.1
Admin panel: 1.10.37.1
Gantry 5:  5.5.15
Template by Rocket Theme
