### ISSUE TITLE
How to add math captcha?

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-plugin-form#584]
From a docs:
https://learn.getgrav.org/17/forms/forms/fields-available#basic-captcha-field

It works:
```
basic-captcha:
            type: basic-captcha
            placeholder: copy the 6 characters
            label: Are you human?
...

process:
        basic-captcha:
            message: Humanity verification failed, please try again...
```

<img width="347" alt="image" src="https://user-images.githubusercontent.com/7556290/208124873-956610f6-1b12-4894-8124-44e5a19328dc.png">

But how to add math type? adding `type: math` show errors.
