### ISSUE TITLE
Revisit: Field 'file' does not save file when used in front-end form

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-form#588]
This issue has been mentioned before, but hasn't been address properly sofar.

Note: **This issue only occurs in front-end forms**, not when used in blueprints.

The following form does **not** save the file:
```
form:
    name: upload
    fields:
      myfile:
        type: file
        label: Uploads
        destination: 'user/data/upload'
        multiple: true
        autofocus: false
        accept:
          - image/* 
    buttons:
      - type: submit
        value: Submit
    process:
      reset: true
      message: Thanks!
```
In this case, action 'reset' is performed before action 'upload'. Since 'reset' clears the flash containing the upload info, there is nothing to save anymore...

**Workarounds** until issue has been fixed:
- Add action 'upload' in form definition. Like:
  ```
  process:
    upload: true 
    reset: true
    message: Thanks!
  ```
- Remove action 'reset', but this has unwanted side effects.
