### ISSUE TITLE
type: select with multiple: true does not (de-)serialize properly

### ISSUE THREAD

**Issue by noBlubb** [getgrav/grav-plugin-form#76]
When using a select input with multiple set to true the (de-)serialization fails.
validate: type: array does not work as expected: Validation fails
validate: type: commalist works, but does not deserialize properly

```
topics:
    - 'coaching,mediation'
```

This is the generated YAML for this field definition:

```
header.topics:
              type: select
              label: ...
              help: ...
              '@data-options': '\Grav\Theme\Glueck::topics'
              multiple: true
              default: ''
              validate:
                type: commalist
```

Where `topics` is a public static function that returns an array `['fuu' => 'bar']`

I checked that `field.options` is indeed my provided array. However `value` seems to be an array with only one element: `['coaching,mediation']`. My quick`n`dirty solution for the moment is to fetch the first element of the value array and check if `coaching` is in `coaching,mediation`\- works, but of course not really nice: `(field.multiple and text in value|first)`

```
{% for key, text in field.options %}
            <option {% if key == value or (field.multiple and text in value|first) %}selected="selected"{% endif %} value="{{ field.multiple ? text : key }}">{% if grav.twig.twig.filters['tu'] is defined %}{{ text|tu }}{% else %}{{ text|t }}{% endif %}</option>
            {% endfor %}
```

Another issue I found when using the select field:

```
{% block global_attributes %}
    data-grav-selectize="{{ (field.selectize is defined ? field.selectize : {})|json_encode()|e('html_attr') }}"
    {{ parent() }}
{% endblock %}
```

Using `e('html_attr')` after `json_encode()` results in having the empty array serialized as html entities, which is not working. I found this to be still existent here https://github.com/getgrav/grav-plugin-form/blob/develop/templates/forms/fields/select/select.html.twig#L4 and i would presume that this still is an issue.

I am using the latest stable version (1.0.10) and up to date plugins. If this has been fixed in the meantime, ignore this :)
